//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//

package com.pdfview.impl.FOP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"title",
"description",
"type",
"formulationType",
"formulation",
"originator",
"lastUpdateUser",
"revision",
"originated",
"segment",
"phase",
"owner",
"releaseDate",
"effectiveDate",
"expirationDate",
"previousRevisionObsoleteDate",
"reasonforChange",
"isProductCertificationorLocalStandardsComplianceStatementRequired",
"productDosePerUse",
"productDoseperUseUoM",
"modeofProductDisposal",
"expectedFrequencyofUse",
"expectedFrequencyofUseUoM",
"manufacturingStatus",
"brand",
"productExtraVariant",
"productForm",
"classdata",
"subClassdata",
"reportedFunction",
"baseUnitOfMeasure",
"onshelfProductDensity",
"densityUnitofMeasure",
"baseQuantity",
"sapBOMBaseQTY",
"localDescription",
"otherNames",
"intendedMarkets",
"replacedProductName",
"uniqueFormulaIdentifier",
"comments",
"obsoleteDate",
"obsoleteComment"

})



@XmlRootElement(name = "Attributes", namespace = "")
public class Attributes {
	@XmlElement(name = "Title", namespace = "") 
	 protected String title;
	@XmlElement(name = "Description", namespace = "") 
	 protected String description;
	@XmlElement(name = "Type", namespace = "") 
	 protected String type;
	@XmlElement(name = "FormulationType", namespace = "") 
	 protected String formulationType;
	@XmlElement(name = "Formulation", namespace = "") 
	 protected String formulation;
	@XmlElement(name = "Originator", namespace = "") 
	 protected String originator;
	@XmlElement(name = "LastUpdateUser", namespace = "") 
	 protected String lastUpdateUser;
	@XmlElement(name = "Revision", namespace = "") 
	 protected String revision;
	@XmlElement(name = "Originated", namespace = "") 
	 protected String originated;
	@XmlElement(name = "Segment", namespace = "") 
	 protected String segment;
	@XmlElement(name = "Phase", namespace = "") 
	 protected String phase;
	@XmlElement(name = "Owner", namespace = "") 
	 protected String owner;
	@XmlElement(name = "ReleaseDate", namespace = "") 
	 protected String releaseDate;
	@XmlElement(name = "EffectiveDate", namespace = "") 
	 protected String effectiveDate;
	@XmlElement(name = "ExpirationDate", namespace = "") 
	 protected String expirationDate;
	@XmlElement(name = "PreviousRevisionObsoleteDate", namespace = "") 
	 protected String previousRevisionObsoleteDate;
	@XmlElement(name = "ReasonforChange", namespace = "") 
	 protected String reasonforChange;
	@XmlElement(name = "IsProductCertificationorLocalStandardsComplianceStatementRequired", namespace = "") 
	 protected String isProductCertificationorLocalStandardsComplianceStatementRequired;
	@XmlElement(name = "ProductDosePerUse", namespace = "") 
	 protected String productDosePerUse;
	@XmlElement(name = "ProductDoseperUseUoM", namespace = "") 
	 protected String productDoseperUseUoM;
	@XmlElement(name = "ModeofProductDisposal", namespace = "") 
	 protected String modeofProductDisposal;
	@XmlElement(name = "ExpectedFrequencyofUse", namespace = "") 
	 protected String expectedFrequencyofUse;
	@XmlElement(name = "ExpectedFrequencyofUseUoM", namespace = "") 
	 protected String expectedFrequencyofUseUoM;
	@XmlElement(name = "ManufacturingStatus", namespace = "") 
	 protected String manufacturingStatus;
	@XmlElement(name = "Brand", namespace = "") 
	 protected String brand;
	@XmlElement(name = "ProductExtraVariant", namespace = "") 
	 protected String productExtraVariant;
	@XmlElement(name = "ProductForm", namespace = "") 
	 protected String productForm;
	@XmlElement(name = "Classdata", namespace = "") 
	 protected String classdata;
	@XmlElement(name = "SubClassdata", namespace = "") 
	 protected String subClassdata;
	@XmlElement(name = "ReportedFunction", namespace = "") 
	 protected String reportedFunction;
	@XmlElement(name = "BaseUnitOfMeasure", namespace = "") 
	 protected String baseUnitOfMeasure;
	@XmlElement(name = "OnshelfProductDensity", namespace = "") 
	 protected String onshelfProductDensity;
	@XmlElement(name = "DensityUnitofMeasure", namespace = "") 
	 protected String densityUnitofMeasure;
	@XmlElement(name = "BaseQuantity", namespace = "") 
	 protected String baseQuantity;
	@XmlElement(name = "SapBOMBaseQTY", namespace = "") 
	 protected String sapBOMBaseQTY;
	@XmlElement(name = "LocalDescription", namespace = "") 
	 protected String localDescription;
	@XmlElement(name = "OtherNames", namespace = "") 
	 protected String otherNames;
	@XmlElement(name = "IntendedMarkets", namespace = "") 
	 protected String intendedMarkets;
	@XmlElement(name = "ReplacedProductName", namespace = "") 
	 protected String replacedProductName;
	@XmlElement(name = "UniqueFormulaIdentifier", namespace = "") 
	 protected String uniqueFormulaIdentifier;
	@XmlElement(name = "Comments", namespace = "") 
	 protected String comments;
	@XmlElement(name = "ObsoleteDate", namespace = "") 
	 protected String obsoleteDate;
	@XmlElement(name = "ObsoleteComment", namespace = "") 
	 protected String obsoleteComment;
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getFormulationType() {
		return formulationType;
	}
	public void setFormulationType(String formulationType) {
		this.formulationType = formulationType;
	}
	public String getFormulation() {
		return formulation;
	}
	public void setFormulation(String formulation) {
		this.formulation = formulation;
	}
	public String getOriginator() {
		return originator;
	}
	public void setOriginator(String originator) {
		this.originator = originator;
	}
	public String getLastUpdateUser() {
		return lastUpdateUser;
	}
	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}
	public String getRevision() {
		return revision;
	}
	public void setRevision(String revision) {
		this.revision = revision;
	}
	public String getOriginated() {
		return originated;
	}
	public void setOriginated(String originated) {
		this.originated = originated;
	}
	public String getSegment() {
		return segment;
	}
	public void setSegment(String segment) {
		this.segment = segment;
	}
	public String getPhase() {
		return phase;
	}
	public void setPhase(String phase) {
		this.phase = phase;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getReleaseDate() {
		return releaseDate;
	}
	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}
	public String getEffectiveDate() {
		return effectiveDate;
	}
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	public String getExpirationDate() {
		return expirationDate;
	}
	public void setExpirationDate(String expirationDate) {
		this.expirationDate = expirationDate;
	}
	public String getPreviousRevisionObsoleteDate() {
		return previousRevisionObsoleteDate;
	}
	public void setPreviousRevisionObsoleteDate(String previousRevisionObsoleteDate) {
		this.previousRevisionObsoleteDate = previousRevisionObsoleteDate;
	}
	public String getReasonforChange() {
		return reasonforChange;
	}
	public void setReasonforChange(String reasonforChange) {
		this.reasonforChange = reasonforChange;
	}
	public String getIsProductCertificationorLocalStandardsComplianceStatementRequired() {
		return isProductCertificationorLocalStandardsComplianceStatementRequired;
	}
	public void setIsProductCertificationorLocalStandardsComplianceStatementRequired(
			String isProductCertificationorLocalStandardsComplianceStatementRequired) {
		this.isProductCertificationorLocalStandardsComplianceStatementRequired = isProductCertificationorLocalStandardsComplianceStatementRequired;
	}
	public String getProductDosePerUse() {
		return productDosePerUse;
	}
	public void setProductDosePerUse(String productDosePerUse) {
		this.productDosePerUse = productDosePerUse;
	}
	public String getProductDoseperUseUoM() {
		return productDoseperUseUoM;
	}
	public void setProductDoseperUseUoM(String productDoseperUseUoM) {
		this.productDoseperUseUoM = productDoseperUseUoM;
	}
	public String getModeofProductDisposal() {
		return modeofProductDisposal;
	}
	public void setModeofProductDisposal(String modeofProductDisposal) {
		this.modeofProductDisposal = modeofProductDisposal;
	}
	public String getExpectedFrequencyofUse() {
		return expectedFrequencyofUse;
	}
	public void setExpectedFrequencyofUse(String expectedFrequencyofUse) {
		this.expectedFrequencyofUse = expectedFrequencyofUse;
	}
	public String getExpectedFrequencyofUseUoM() {
		return expectedFrequencyofUseUoM;
	}
	public void setExpectedFrequencyofUseUoM(String expectedFrequencyofUseUoM) {
		this.expectedFrequencyofUseUoM = expectedFrequencyofUseUoM;
	}
	public String getManufacturingStatus() {
		return manufacturingStatus;
	}
	public void setManufacturingStatus(String manufacturingStatus) {
		this.manufacturingStatus = manufacturingStatus;
	}
	public String getBrand() {
		return brand;
	}
	public void setBrand(String brand) {
		this.brand = brand;
	}
	public String getProductExtraVariant() {
		return productExtraVariant;
	}
	public void setProductExtraVariant(String productExtraVariant) {
		this.productExtraVariant = productExtraVariant;
	}
	public String getProductForm() {
		return productForm;
	}
	public void setProductForm(String productForm) {
		this.productForm = productForm;
	}
	public String getClassdata() {
		return classdata;
	}
	public void setClassdata(String classdata) {
		this.classdata = classdata;
	}
	public String getSubClassdata() {
		return subClassdata;
	}
	public void setSubClassdata(String subClassdata) {
		this.subClassdata = subClassdata;
	}
	public String getReportedFunction() {
		return reportedFunction;
	}
	public void setReportedFunction(String reportedFunction) {
		this.reportedFunction = reportedFunction;
	}
	public String getBaseUnitOfMeasure() {
		return baseUnitOfMeasure;
	}
	public void setBaseUnitOfMeasure(String baseUnitOfMeasure) {
		this.baseUnitOfMeasure = baseUnitOfMeasure;
	}
	public String getOnshelfProductDensity() {
		return onshelfProductDensity;
	}
	public void setOnshelfProductDensity(String onshelfProductDensity) {
		this.onshelfProductDensity = onshelfProductDensity;
	}
	public String getDensityUnitofMeasure() {
		return densityUnitofMeasure;
	}
	public void setDensityUnitofMeasure(String densityUnitofMeasure) {
		this.densityUnitofMeasure = densityUnitofMeasure;
	}
	public String getBaseQuantity() {
		return baseQuantity;
	}
	public void setBaseQuantity(String baseQuantity) {
		this.baseQuantity = baseQuantity;
	}
	public String getSapBOMBaseQTY() {
		return sapBOMBaseQTY;
	}
	public void setSapBOMBaseQTY(String sapBOMBaseQTY) {
		this.sapBOMBaseQTY = sapBOMBaseQTY;
	}
	public String getLocalDescription() {
		return localDescription;
	}
	public void setLocalDescription(String localDescription) {
		this.localDescription = localDescription;
	}
	public String getOtherNames() {
		return otherNames;
	}
	public void setOtherNames(String otherNames) {
		this.otherNames = otherNames;
	}
	public String getIntendedMarkets() {
		return intendedMarkets;
	}
	public void setIntendedMarkets(String intendedMarkets) {
		this.intendedMarkets = intendedMarkets;
	}
	public String getReplacedProductName() {
		return replacedProductName;
	}
	public void setReplacedProductName(String replacedProductName) {
		this.replacedProductName = replacedProductName;
	}
	public String getUniqueFormulaIdentifier() {
		return uniqueFormulaIdentifier;
	}
	public void setUniqueFormulaIdentifier(String uniqueFormulaIdentifier) {
		this.uniqueFormulaIdentifier = uniqueFormulaIdentifier;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public String getObsoleteDate() {
		return obsoleteDate;
	}
	public void setObsoleteDate(String obsoleteDate) {
		this.obsoleteDate = obsoleteDate;
	}
	public String getObsoleteComment() {
		return obsoleteComment;
	}
	public void setObsoleteComment(String obsoleteComment) {
		this.obsoleteComment = obsoleteComment;
	}
	
	}
