//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//


package com.pdfview.impl.FOP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.pdfview.impl.APP.CountryClearances;
import com.pdfview.impl.APP.Dgcs;
import com.pdfview.impl.APP.MasterAttributes;
import com.pdfview.impl.APP.MaterialsProduced;
import com.pdfview.impl.APP.WeightCharacteristic;
import com.pdfview.impl.FPP.Certifications;
import com.pdfview.impl.FPP.DerivedParts;
import com.pdfview.impl.FPP.Ghss;
import com.pdfview.impl.FPP.MasterSpecifications;
import com.pdfview.impl.FPP.Organizations;
import com.pdfview.impl.FPP.Ownership;
import com.pdfview.impl.FPP.PerformanceCharacteristics;
import com.pdfview.impl.FPP.Plants;
import com.pdfview.impl.FPP.ReferenceDocuments;
import com.pdfview.impl.FPP.RelatedATS;
import com.pdfview.impl.FPP.RelatedSpecifications;
import com.pdfview.impl.FPP.SapBOMAsFeds;
import com.pdfview.impl.FPP.StabilityResults;
import com.pdfview.impl.common.GenericModel;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"attributes",
	"organizations",
	"ghss",
    "dgcs",
	"storageTransportationData",
	"chemicalPhysicalProertiesGHS",
	"chemicalPhysicalProertiesWC",
	"chemicalandPhysicalProertiesEnginuity",
	"stabilityResults",
	"formulationProcessData",
	"formulationProcessSubstitutes",
	"materialsCompositions",
	 "sapBOMAsFeds",
	 "countryClearances",
	 "referenceDocuments",
	 "derivedParts",
	 "plants",
	 "relatedATS",
	 "materialsProduced",
	 "performanceCharacteristics",
	 "weightCharacteristic",
	 "certifications",
	 "ownership",
	 "relatedSpecifications",
	 "masterAttributes",
	 "masterSpecifications",
	 "genericModel"
	 
})
@XmlRootElement(name = "Basic", namespace = "")
public class Basic {

	@XmlElement(name = "Attributes", namespace = "")
	protected Attributes attributes;
	@XmlElement(name = "StorageTransportationData", namespace = "")
	protected StorageTransportationData storageTransportationData;

	@XmlElement(name = "ChemicalPhysicalProertiesGHS", namespace = "")
	protected ChemicalPhysicalProertiesGHS chemicalPhysicalProertiesGHS;
	
	@XmlElement(name = "ChemicalPhysicalProertiesWC", namespace = "")
	protected ChemicalPhysicalProertiesWC chemicalPhysicalProertiesWC;
	
	@XmlElement(name = "ChemicalandPhysicalProertiesEnginuity", namespace = "")
	protected ChemicalandPhysicalProertiesEnginuity chemicalandPhysicalProertiesEnginuity;
	@XmlElement(name = "FormulationProcessData", namespace = "")
	protected FormulationProcessData formulationProcessData;
	@XmlElement(name = "FormulationProcessSubstitutes", namespace = "")
	protected FormulationProcessSubstitutes formulationProcessSubstitutes;
	@XmlElement(name = "MaterialsCompositions", namespace = "")
	protected MaterialsCompositions materialsCompositions;
	@XmlElement(name = "SapBOMAsFeds", namespace = "")
	protected SapBOMAsFeds sapBOMAsFeds;
	@XmlElement(name = "Ghss", namespace = "")
	protected Ghss ghss;
	@XmlElement(name = "Dgcs", namespace = "")
	protected Dgcs dgcs;
	@XmlElement(name = "Organizations", namespace = "")
	protected Organizations organizations;
	@XmlElement(name = "StabilityResults", namespace = "")
	protected StabilityResults stabilityResults;
	@XmlElement(name = "CountryClearances", namespace = "")
	protected CountryClearances countryClearances;
	@XmlElement(name = "ReferenceDocuments", namespace = "")
	protected ReferenceDocuments  referenceDocuments;
	@XmlElement(name = "DerivedParts", namespace = "")
	protected DerivedParts derivedParts;
	@XmlElement(name = "Plants", namespace = "")
	protected Plants plants;
	@XmlElement(name = "RelatedATS", namespace = "")
	protected RelatedATS relatedATS;
	@XmlElement(name = "MaterialsProduced", namespace = "")
	protected MaterialsProduced materialsProduced;
	@XmlElement(name = "WeightCharacteristic", namespace = "")
	protected WeightCharacteristic weightCharacteristic;
	@XmlElement(name = "PerformanceCharacteristics", namespace = "")
	protected PerformanceCharacteristics  performanceCharacteristics;
	@XmlElement(name = "Certifications", namespace = "")
	protected Certifications  certifications;
	@XmlElement(name = "Ownership", namespace = "")
	protected Ownership ownership;
	@XmlElement(name = "RelatedSpecifications", namespace = "")
	protected RelatedSpecifications relatedSpecifications;
	@XmlElement(name = "MasterAttributes", namespace = "")
	protected MasterAttributes masterAttributes;
	@XmlElement(name="MasterSpecifications", namespace="")
	protected MasterSpecifications masterSpecifications;
	@XmlElement(name = "GenericModel", namespace = "")
	protected GenericModel genericModel;
	
	
	public Ghss getGhss() {
		return ghss;
	}
	public void setGhss(Ghss ghss) {
		this.ghss = ghss;
	}
	public Dgcs getDgcs() {
		return dgcs;
	}
	public void setDgcs(Dgcs dgcs) {
		this.dgcs = dgcs;
	}
	public Organizations getOrganizations() {
		return organizations;
	}
	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}
	public StabilityResults getStabilityResults() {
		return stabilityResults;
	}
	public void setStabilityResults(StabilityResults stabilityResults) {
		this.stabilityResults = stabilityResults;
	}
	public CountryClearances getCountryClearances() {
		return countryClearances;
	}
	public void setCountryClearances(CountryClearances countryClearances) {
		this.countryClearances = countryClearances;
	}
	public ReferenceDocuments getReferenceDocuments() {
		return referenceDocuments;
	}
	public void setReferenceDocuments(ReferenceDocuments referenceDocuments) {
		this.referenceDocuments = referenceDocuments;
	}
	public DerivedParts getDerivedParts() {
		return derivedParts;
	}
	public void setDerivedParts(DerivedParts derivedParts) {
		this.derivedParts = derivedParts;
	}
	public Plants getPlants() {
		return plants;
	}
	public void setPlants(Plants plants) {
		this.plants = plants;
	}
	public RelatedATS getRelatedATS() {
		return relatedATS;
	}
	public void setRelatedATS(RelatedATS relatedATS) {
		this.relatedATS = relatedATS;
	}
	public MaterialsProduced getMaterialsProduced() {
		return materialsProduced;
	}
	public void setMaterialsProduced(MaterialsProduced materialsProduced) {
		this.materialsProduced = materialsProduced;
	}
	public WeightCharacteristic getWeightCharacteristic() {
		return weightCharacteristic;
	}
	public void setWeightCharacteristic(WeightCharacteristic weightCharacteristic) {
		this.weightCharacteristic = weightCharacteristic;
	}
	public PerformanceCharacteristics getPerformanceCharacteristics() {
		return performanceCharacteristics;
	}
	public void setPerformanceCharacteristics(PerformanceCharacteristics performanceCharacteristics) {
		this.performanceCharacteristics = performanceCharacteristics;
	}
	public Certifications getCertifications() {
		return certifications;
	}
	public void setCertifications(Certifications certifications) {
		this.certifications = certifications;
	}
	public Ownership getOwnership() {
		return ownership;
	}
	public void setOwnership(Ownership ownership) {
		this.ownership = ownership;
	}
	public RelatedSpecifications getRelatedSpecifications() {
		return relatedSpecifications;
	}
	public void setRelatedSpecifications(RelatedSpecifications relatedSpecifications) {
		this.relatedSpecifications = relatedSpecifications;
	}
	public MasterAttributes getMasterAttributes() {
		return masterAttributes;
	}
	public void setMasterAttributes(MasterAttributes masterAttributes) {
		this.masterAttributes = masterAttributes;
	}
	public MasterSpecifications getMasterSpecifications() {
		return masterSpecifications;
	}
	public void setMasterSpecifications(MasterSpecifications masterSpecifications) {
		this.masterSpecifications = masterSpecifications;
	}
	public Attributes getAttributes() {
		return attributes;
	}
	public void setAttributes(Attributes attributes) {
		this.attributes = attributes;
	}
	public StorageTransportationData getStorageTransportationData() {
		return storageTransportationData;
	}
	public void setStorageTransportationData(StorageTransportationData storageTransportationData) {
		this.storageTransportationData = storageTransportationData;
	}
	public ChemicalPhysicalProertiesGHS getChemicalPhysicalProertiesGHS() {
		return chemicalPhysicalProertiesGHS;
	}
	public void setChemicalPhysicalProertiesGHS(
			ChemicalPhysicalProertiesGHS chemicalPhysicalProertiesGHS) {
		this.chemicalPhysicalProertiesGHS = chemicalPhysicalProertiesGHS;
	}
	public ChemicalPhysicalProertiesWC getChemicalPhysicalProertiesWC() {
		return chemicalPhysicalProertiesWC;
	}
	public void setChemicalPhysicalProertiesWC(
			ChemicalPhysicalProertiesWC chemicalPhysicalProertiesWC) {
		this.chemicalPhysicalProertiesWC = chemicalPhysicalProertiesWC;
	}
	public ChemicalandPhysicalProertiesEnginuity getChemicalandPhysicalProertiesEnginuity() {
		return chemicalandPhysicalProertiesEnginuity;
	}
	public void setChemicalandPhysicalProertiesEnginuity(
			ChemicalandPhysicalProertiesEnginuity chemicalandPhysicalProertiesEnginuity) {
		this.chemicalandPhysicalProertiesEnginuity = chemicalandPhysicalProertiesEnginuity;
	}
	public FormulationProcessData getFormulationProcessData() {
		return formulationProcessData;
	}
	public void setFormulationProcessData(FormulationProcessData formulationProcessData) {
		this.formulationProcessData = formulationProcessData;
	}
	public FormulationProcessSubstitutes getFormulationProcessSubstitutes() {
		return formulationProcessSubstitutes;
	}
	public void setFormulationProcessSubstitutes(FormulationProcessSubstitutes formulationProcessSubstitutes) {
		this.formulationProcessSubstitutes = formulationProcessSubstitutes;
	}
	public MaterialsCompositions getMaterialsCompositions() {
		return materialsCompositions;
	}
	public void setMaterialsCompositions(MaterialsCompositions materialsCompositions) {
		this.materialsCompositions = materialsCompositions;
	}
	public SapBOMAsFeds getSapBOMAsFeds() {
		return sapBOMAsFeds;
	}
	public void setSapBOMAsFeds(SapBOMAsFeds sapBOMAsFeds) {
		this.sapBOMAsFeds = sapBOMAsFeds;
	}
	public GenericModel getGenericModel() {
		return genericModel;
	}
	public void setGenericModel(GenericModel genericModel) {
		this.genericModel = genericModel;
	}



}
