//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//


package com.pdfview.impl.DPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.pdfview.impl.FPP.Organizations;
import com.pdfview.impl.FPP.Ownership;
import com.pdfview.impl.APP.CountryClearances;
import com.pdfview.impl.APP.Dgcs;
import com.pdfview.impl.APP.MasterAttributes;
import com.pdfview.impl.APP.MaterialsProduced;
import com.pdfview.impl.DPP.StorageTransportationData;
import com.pdfview.impl.FOP.MaterialsCompositions;
import com.pdfview.impl.APP.WeightCharacteristic;
import com.pdfview.impl.FPP.AllBillOfMaterial;
import com.pdfview.impl.FPP.Certifications;
import com.pdfview.impl.FPP.DerivedParts;
import com.pdfview.impl.FPP.Ghss;
import com.pdfview.impl.FPP.LifeCycle;
import com.pdfview.impl.FPP.MasterSpecifications;
import com.pdfview.impl.FPP.Notes;
import com.pdfview.impl.FPP.PerformanceCharacteristics;
import com.pdfview.impl.FPP.Plants;
import com.pdfview.impl.FPP.ReferenceDocuments;
import com.pdfview.impl.FPP.RelatedATS;
import com.pdfview.impl.FPP.RelatedSpecifications;
import com.pdfview.impl.FPP.SapBOMAsFeds;
import com.pdfview.impl.FPP.SecurityClasses;
import com.pdfview.impl.FPP.StabilityResults;
import com.pdfview.impl.common.GenericModel;




@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributes",
    "organizations",
    "storageTransportationData",
    "notes",
    "stabilityResults",
    "weightCharacteristic",
    "certifications",
    "plants",
    "referenceDocuments",
    "ghss",
    "dgcs",
    "lifeCycle",
    "ownership",
    "countryClearances",
    "relatedATS",
    "securityClasses",
    "materialsProduced",
    "derivedParts",
    "allBillOfMaterial",
    "relatedSpecifications",
    "masterAttributes",
    "performanceCharacteristics",
    "masterSpecifications",
    "supplierEquivalents",
    "manufacturerEquivalents",
    "sapBOMAsFeds",
    "materialsCompositions",
    "genericModel"
})
@XmlRootElement(name = "Basic", namespace = "")
public class Basic {

    @XmlElement(name = "Attributes", namespace = "")
    protected Attributes attributes;
  
    @XmlElement(name = "Organizations", namespace = "")
    protected Organizations organizations;
    @XmlElement(name = "StorageTransportationData", namespace = "")
    protected StorageTransportationData storageTransportationData;
    @XmlElement(name = "Notes", namespace = "")
	protected Notes notes;
	@XmlElement(name = "StabilityResults", namespace = "")
	protected StabilityResults stabilityResults;
	@XmlElement(name = "WeightCharacteristic", namespace = "")
	protected WeightCharacteristic weightCharacteristic;
	@XmlElement(name = "Certifications", namespace = "")
	protected Certifications  certifications;
	@XmlElement(name = "Plants", namespace = "")
	protected Plants plants;
	@XmlElement(name = "ReferenceDocuments", namespace = "")
	protected ReferenceDocuments  referenceDocuments;
	@XmlElement(name = "Ghss", namespace = "")
	protected Ghss ghss;
	@XmlElement(name = "Dgcs", namespace = "")
	protected Dgcs dgcs;
	@XmlElement(name = "Ownership", namespace = "")
	protected Ownership ownership;
	@XmlElement(name = "LifeCycle", namespace = "")
	protected LifeCycle lifeCycle;
	@XmlElement(name = "CountryClearances", namespace = "")
	protected CountryClearances countryClearances;
	@XmlElement(name = "SecurityClasses", namespace = "")
	protected SecurityClasses securityClasses;
	@XmlElement(name = "RelatedATS", namespace = "")
	protected RelatedATS relatedATS;
	@XmlElement(name = "MaterialsProduced", namespace = "")
	protected MaterialsProduced materialsProduced;
	@XmlElement(name = "DerivedParts", namespace = "")
	protected DerivedParts derivedParts;
	@XmlElement(name = "AllBillOfMaterial", namespace = "")
	protected AllBillOfMaterial allBillOfMaterial;
	@XmlElement(name = "RelatedSpecifications", namespace = "")
	protected RelatedSpecifications relatedSpecifications;
	@XmlElement(name = "MasterAttributes", namespace = "")
	protected MasterAttributes masterAttributes;
	@XmlElement(name="PerformanceCharacteristics", namespace="")
	protected PerformanceCharacteristics performanceCharacteristics;
	@XmlElement(name="MasterSpecifications", namespace="")
	protected MasterSpecifications masterSpecifications;
	@XmlElement(name="SupplierEquivalents", namespace="")
	protected SupplierEquivalents supplierEquivalents;
	@XmlElement(name="ManufacturerEquivalents", namespace="")
	protected ManufacturerEquivalents manufacturerEquivalents;
	@XmlElement(name = "SapBOMAsFeds", namespace = "")
	protected SapBOMAsFeds sapBOMAsFeds;
	@XmlElement(name = "MaterialsCompositions", namespace = "")
	protected MaterialsCompositions materialsCompositions;
	@XmlElement(name = "GenericModel", namespace = "")
	protected GenericModel genericModel;
	
	public Attributes getAttributes() {
		return attributes;
	}
	public void setAttributes(Attributes attributes) {
		this.attributes = attributes;
	}
	public Organizations getOrganizations() {
		return organizations;
	}
	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}
	public StorageTransportationData getStorageTransportationData() {
		return storageTransportationData;
	}
	public void setStorageTransportationData(StorageTransportationData storageTransportationData) {
		this.storageTransportationData = storageTransportationData;
	}
	public Notes getNotes() {
		return notes;
	}
	public void setNotes(Notes notes) {
		this.notes = notes;
	}
	public StabilityResults getStabilityResults() {
		return stabilityResults;
	}
	public void setStabilityResults(StabilityResults stabilityResults) {
		this.stabilityResults = stabilityResults;
	}
	public WeightCharacteristic getWeightCharacteristic() {
		return weightCharacteristic;
	}
	public void setWeightCharacteristic(WeightCharacteristic weightCharacteristic) {
		this.weightCharacteristic = weightCharacteristic;
	}
	public Certifications getCertifications() {
		return certifications;
	}
	public void setCertifications(Certifications certifications) {
		this.certifications = certifications;
	}
	public Plants getPlants() {
		return plants;
	}
	public void setPlants(Plants plants) {
		this.plants = plants;
	}
	public ReferenceDocuments getReferenceDocuments() {
		return referenceDocuments;
	}
	public void setReferenceDocuments(ReferenceDocuments referenceDocuments) {
		this.referenceDocuments = referenceDocuments;
	}
	public Ghss getGhss() {
		return ghss;
	}
	public void setGhss(Ghss ghss) {
		this.ghss = ghss;
	}
	public Dgcs getDgcs() {
		return dgcs;
	}
	public void setDgcs(Dgcs dgcs) {
		this.dgcs = dgcs;
	}
	public Ownership getOwnership() {
		return ownership;
	}
	public void setOwnership(Ownership ownership) {
		this.ownership = ownership;
	}
	public LifeCycle getLifeCycle() {
		return lifeCycle;
	}
	public void setLifeCycle(LifeCycle lifeCycle) {
		this.lifeCycle = lifeCycle;
	}
	public CountryClearances getCountryClearances() {
		return countryClearances;
	}
	public void setCountryClearances(CountryClearances countryClearances) {
		this.countryClearances = countryClearances;
	}
	public SecurityClasses getSecurityClasses() {
		return securityClasses;
	}
	public void setSecurityClasses(SecurityClasses securityClasses) {
		this.securityClasses = securityClasses;
	}
	public RelatedATS getRelatedATS() {
		return relatedATS;
	}
	public void setRelatedATS(RelatedATS relatedATS) {
		this.relatedATS = relatedATS;
	}
	public MaterialsProduced getMaterialsProduced() {
		return materialsProduced;
	}
	public void setMaterialsProduced(MaterialsProduced materialsProduced) {
		this.materialsProduced = materialsProduced;
	}
	public DerivedParts getDerivedParts() {
		return derivedParts;
	}
	public void setDerivedParts(DerivedParts derivedParts) {
		this.derivedParts = derivedParts;
	}
	public AllBillOfMaterial getAllBillOfMaterial() {
		return allBillOfMaterial;
	}
	public void setAllBillOfMaterial(AllBillOfMaterial allBillOfMaterial) {
		this.allBillOfMaterial = allBillOfMaterial;
	}
	public RelatedSpecifications getRelatedSpecifications() {
		return relatedSpecifications;
	}
	public void setRelatedSpecifications(RelatedSpecifications relatedSpecifications) {
		this.relatedSpecifications = relatedSpecifications;
	}
	public MasterAttributes getMasterAttributes() {
		return masterAttributes;
	}
	public void setMasterAttributes(MasterAttributes masterAttributes) {
		this.masterAttributes = masterAttributes;
	}
	public PerformanceCharacteristics getPerformanceCharacteristics() {
		return performanceCharacteristics;
	}
	public void setPerformanceCharacteristics(PerformanceCharacteristics performanceCharacteristics) {
		this.performanceCharacteristics = performanceCharacteristics;
	}
	public MasterSpecifications getMasterSpecifications() {
		return masterSpecifications;
	}
	public void setMasterSpecifications(MasterSpecifications masterSpecifications) {
		this.masterSpecifications = masterSpecifications;
	}
	public SupplierEquivalents getSupplierEquivalents() {
		return supplierEquivalents;
	}
	public void setSupplierEquivalents(SupplierEquivalents supplierEquivalents) {
		this.supplierEquivalents = supplierEquivalents;
	}
	public ManufacturerEquivalents getManufacturerEquivalents() {
		return manufacturerEquivalents;
	}
	public void setManufacturerEquivalents(ManufacturerEquivalents manufacturerEquivalents) {
		this.manufacturerEquivalents = manufacturerEquivalents;
	}
	public SapBOMAsFeds getSapBOMAsFeds() {
		return sapBOMAsFeds;
	}
	public void setSapBOMAsFeds(SapBOMAsFeds sapBOMAsFeds) {
		this.sapBOMAsFeds = sapBOMAsFeds;
	}
	public MaterialsCompositions getMaterialsCompositions() {
		return materialsCompositions;
	}
	public void setMaterialsCompositions(MaterialsCompositions materialsCompositions) {
		this.materialsCompositions = materialsCompositions;
	}
	public GenericModel getGenericModel() {
		return genericModel;
	}
	public void setGenericModel(GenericModel genericModel) {
		this.genericModel = genericModel;
	}

	
}
