//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//

package com.pdfview.impl.PMP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"title",
		"type",
		"description",
		"specificationSubType",
		"revision",
		"originated",
		"phase",
		"owner",
		"releaseDate",
		"effectiveDate",
		"expirationDate",
		"previousRevisionObsoleteDate",
		"cO",
		"manufacturingStatus",
		"partFamily",
		"reasonforChange",
		"brand",
		"reportedFunction",
		"classdata",
		"subClassdata",
		"localDescription",
		"otherNames",
		"baseUnitOfMeasure",
		"packagingMaterialType",
		"packagingComponentType",
		"packagingSize",
		"packagingSizeUoM",
		"packagingTechnology",
		"partColor",
		"printingProcess",
		"decorationDetails",
		"shippingInformation",
		"labelingInformation",
		"storageInformation",
		"storageTemperatureLimits",
		"storageHumidityLimits",
		"comments",
		"obsoleteDate",
		"obsoleteComment",
		"classification",
		"structuredReleaseCriteriaRequired",
		"originator",
		"lastUpdateUser",
		"segment",
		"preferredMaterial",
		"hasMultipleGTINsonArtwork",
		"storageConditions"

})


@XmlRootElement(name = "Attributes", namespace = "")
public class Attributes {
	@XmlElement(name = "Title", namespace = "") 
	protected String title;
	@XmlElement(name = "Type", namespace = "") 
	protected String type;
	@XmlElement(name = "Description", namespace = "") 
	protected String description;
	@XmlElement(name = "SpecificationSubType", namespace = "") 
	protected String specificationSubType;
	@XmlElement(name = "Revision", namespace = "") 
	protected String revision;
	@XmlElement(name = "Originated", namespace = "") 
	protected String originated;
	@XmlElement(name = "Phase", namespace = "") 
	protected String phase;
	@XmlElement(name = "Owner", namespace = "") 
	protected String owner;
	@XmlElement(name = "ReleaseDate", namespace = "") 
	protected String releaseDate;
	@XmlElement(name = "EffectiveDate", namespace = "") 
	protected String effectiveDate;
	@XmlElement(name = "ExpirationDate", namespace = "") 
	protected String expirationDate;
	@XmlElement(name = "PreviousRevisionObsoleteDate", namespace = "") 
	protected String previousRevisionObsoleteDate;
	@XmlElement(name = "CO", namespace = "") 
	protected String cO;
	@XmlElement(name = "ManufacturingStatus", namespace = "") 
	protected String manufacturingStatus;
	@XmlElement(name = "PartFamily", namespace = "") 
	protected String partFamily;
	@XmlElement(name = "ReasonforChange", namespace = "") 
	protected String reasonforChange;
	@XmlElement(name = "Brand", namespace = "") 
	protected String brand;
	@XmlElement(name = "ReportedFunction", namespace = "") 
	protected String reportedFunction;
	@XmlElement(name = "Classdata", namespace = "") 
	protected String classdata;
	@XmlElement(name = "SubClassdata", namespace = "") 
	protected String subClassdata;
	@XmlElement(name = "LocalDescription", namespace = "") 
	protected String localDescription;
	@XmlElement(name = "OtherNames", namespace = "") 
	protected String otherNames;
	@XmlElement(name = "BaseUnitOfMeasure", namespace = "") 
	protected String baseUnitOfMeasure;
	@XmlElement(name = "PackagingMaterialType", namespace = "") 
	protected String packagingMaterialType;
	@XmlElement(name = "PackagingComponentType", namespace = "") 
	protected String packagingComponentType;
	@XmlElement(name = "PackagingSize", namespace = "") 
	protected String packagingSize;
	@XmlElement(name = "PackagingSizeUoM", namespace = "") 
	protected String packagingSizeUoM;
	@XmlElement(name = "PackagingTechnology", namespace = "") 
	protected String packagingTechnology;
	@XmlElement(name = "PartColor", namespace = "") 
	protected String partColor;
	@XmlElement(name = "PrintingProcess", namespace = "") 
	protected String printingProcess;
	@XmlElement(name = "DecorationDetails", namespace = "") 
	protected String decorationDetails;
	@XmlElement(name = "ShippingInformation", namespace = "") 
	protected String shippingInformation;
	@XmlElement(name = "LabelingInformation", namespace = "") 
	protected String labelingInformation;
	@XmlElement(name = "StorageInformation", namespace = "") 
	protected String storageInformation;
	@XmlElement(name = "StorageTemperatureLimits", namespace = "") 
	protected String storageTemperatureLimits;
	@XmlElement(name = "StorageHumidityLimits", namespace = "") 
	protected String storageHumidityLimits;
	@XmlElement(name = "Comments", namespace = "") 
	protected String comments;
	@XmlElement(name = "ObsoleteDate", namespace = "") 
	protected String obsoleteDate;
	@XmlElement(name = "ObsoleteComment", namespace = "") 
	protected String obsoleteComment;
	@XmlElement(name = "Classification", namespace = "") 
	protected String classification;
	@XmlElement(name = "StructuredReleaseCriteriaRequired", namespace = "") 
	protected String structuredReleaseCriteriaRequired;
	@XmlElement(name = "Originator", namespace = "") 
	protected String originator;
	@XmlElement(name = "LastUpdateUser", namespace = "") 
	protected String lastUpdateUser;
	@XmlElement(name = "Segment", namespace = "") 
	protected String segment;
	@XmlElement(name = "PreferredMaterial", namespace = "") 
	protected String preferredMaterial;
	@XmlElement(name = "HasMultipleGTINsonArtwork", namespace = "") 
	protected String hasMultipleGTINsonArtwork;
	@XmlElement(name = "StorageConditions", namespace = "") 
	protected String storageConditions;
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getSpecificationSubType() {
		return specificationSubType;
	}
	public void setSpecificationSubType(String specificationSubType) {
		this.specificationSubType = specificationSubType;
	}
	public String getRevision() {
		return revision;
	}
	public void setRevision(String revision) {
		this.revision = revision;
	}
	public String getOriginated() {
		return originated;
	}
	public void setOriginated(String originated) {
		this.originated = originated;
	}
	public String getPhase() {
		return phase;
	}
	public void setPhase(String phase) {
		this.phase = phase;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getReleaseDate() {
		return releaseDate;
	}
	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}
	public String getEffectiveDate() {
		return effectiveDate;
	}
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	public String getExpirationDate() {
		return expirationDate;
	}
	public void setExpirationDate(String expirationDate) {
		this.expirationDate = expirationDate;
	}
	public String getPreviousRevisionObsoleteDate() {
		return previousRevisionObsoleteDate;
	}
	public void setPreviousRevisionObsoleteDate(String previousRevisionObsoleteDate) {
		this.previousRevisionObsoleteDate = previousRevisionObsoleteDate;
	}
	public String getcO() {
		return cO;
	}
	public void setcO(String cO) {
		this.cO = cO;
	}
	public String getManufacturingStatus() {
		return manufacturingStatus;
	}
	public void setManufacturingStatus(String manufacturingStatus) {
		this.manufacturingStatus = manufacturingStatus;
	}
	public String getPartFamily() {
		return partFamily;
	}
	public void setPartFamily(String partFamily) {
		this.partFamily = partFamily;
	}
	public String getReasonforChange() {
		return reasonforChange;
	}
	public void setReasonforChange(String reasonforChange) {
		this.reasonforChange = reasonforChange;
	}
	public String getBrand() {
		return brand;
	}
	public void setBrand(String brand) {
		this.brand = brand;
	}
	public String getReportedFunction() {
		return reportedFunction;
	}
	public void setReportedFunction(String reportedFunction) {
		this.reportedFunction = reportedFunction;
	}
	public String getClassdata() {
		return classdata;
	}
	public void setClassdata(String classdata) {
		this.classdata = classdata;
	}
	public String getSubClassdata() {
		return subClassdata;
	}
	public void setSubClassdata(String subClassdata) {
		this.subClassdata = subClassdata;
	}
	public String getLocalDescription() {
		return localDescription;
	}
	public void setLocalDescription(String localDescription) {
		this.localDescription = localDescription;
	}
	public String getOtherNames() {
		return otherNames;
	}
	public void setOtherNames(String otherNames) {
		this.otherNames = otherNames;
	}
	public String getBaseUnitOfMeasure() {
		return baseUnitOfMeasure;
	}
	public void setBaseUnitOfMeasure(String baseUnitOfMeasure) {
		this.baseUnitOfMeasure = baseUnitOfMeasure;
	}
	public String getPackagingMaterialType() {
		return packagingMaterialType;
	}
	public void setPackagingMaterialType(String packagingMaterialType) {
		this.packagingMaterialType = packagingMaterialType;
	}
	public String getPackagingComponentType() {
		return packagingComponentType;
	}
	public void setPackagingComponentType(String packagingComponentType) {
		this.packagingComponentType = packagingComponentType;
	}
	public String getPackagingSize() {
		return packagingSize;
	}
	public void setPackagingSize(String packagingSize) {
		this.packagingSize = packagingSize;
	}
	public String getPackagingSizeUoM() {
		return packagingSizeUoM;
	}
	public void setPackagingSizeUoM(String packagingSizeUoM) {
		this.packagingSizeUoM = packagingSizeUoM;
	}
	public String getPackagingTechnology() {
		return packagingTechnology;
	}
	public void setPackagingTechnology(String packagingTechnology) {
		this.packagingTechnology = packagingTechnology;
	}
	public String getPartColor() {
		return partColor;
	}
	public void setPartColor(String partColor) {
		this.partColor = partColor;
	}
	public String getPrintingProcess() {
		return printingProcess;
	}
	public void setPrintingProcess(String printingProcess) {
		this.printingProcess = printingProcess;
	}
	public String getDecorationDetails() {
		return decorationDetails;
	}
	public void setDecorationDetails(String decorationDetails) {
		this.decorationDetails = decorationDetails;
	}
	public String getShippingInformation() {
		return shippingInformation;
	}
	public void setShippingInformation(String shippingInformation) {
		this.shippingInformation = shippingInformation;
	}
	public String getLabelingInformation() {
		return labelingInformation;
	}
	public void setLabelingInformation(String labelingInformation) {
		this.labelingInformation = labelingInformation;
	}
	public String getStorageInformation() {
		return storageInformation;
	}
	public void setStorageInformation(String storageInformation) {
		this.storageInformation = storageInformation;
	}
	public String getStorageTemperatureLimits() {
		return storageTemperatureLimits;
	}
	public void setStorageTemperatureLimits(String storageTemperatureLimits) {
		this.storageTemperatureLimits = storageTemperatureLimits;
	}
	public String getStorageHumidityLimits() {
		return storageHumidityLimits;
	}
	public void setStorageHumidityLimits(String storageHumidityLimits) {
		this.storageHumidityLimits = storageHumidityLimits;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public String getObsoleteDate() {
		return obsoleteDate;
	}
	public void setObsoleteDate(String obsoleteDate) {
		this.obsoleteDate = obsoleteDate;
	}
	public String getObsoleteComment() {
		return obsoleteComment;
	}
	public void setObsoleteComment(String obsoleteComment) {
		this.obsoleteComment = obsoleteComment;
	}
	public String getClassification() {
		return classification;
	}
	public void setClassification(String classification) {
		this.classification = classification;
	}
	public String getStructuredReleaseCriteriaRequired() {
		return structuredReleaseCriteriaRequired;
	}
	public void setStructuredReleaseCriteriaRequired(
			String structuredReleaseCriteriaRequired) {
		this.structuredReleaseCriteriaRequired = structuredReleaseCriteriaRequired;
	}
	public String getOriginator() {
		return originator;
	}
	public void setOriginator(String originator) {
		this.originator = originator;
	}
	public String getLastUpdateUser() {
		return lastUpdateUser;
	}
	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}
	public String getSegment() {
		return segment;
	}
	public void setSegment(String segment) {
		this.segment = segment;
	}
	public String getPreferredMaterial() {
		return preferredMaterial;
	}
	public void setPreferredMaterial(String preferredMaterial) {
		this.preferredMaterial = preferredMaterial;
	}
	public String getHasMultipleGTINsonArtwork() {
		return hasMultipleGTINsonArtwork;
	}
	public void setHasMultipleGTINsonArtwork(String hasMultipleGTINsonArtwork) {
		this.hasMultipleGTINsonArtwork = hasMultipleGTINsonArtwork;
	}
	public String getStorageConditions() {
		return storageConditions;
	}
	public void setStorageConditions(String storageConditions) {
		this.storageConditions = storageConditions;
	}

}
