//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//


package com.pdfview.impl.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"compactType",
	"compactName",
	"compactRevision",
	"compactRole"

})
@XmlRootElement(name = "GenericModel", namespace = "")
public class GenericModel {

	@XmlElement(name = "CompactType", namespace = "") 
	 protected String compactType;
	@XmlElement(name = "CompactName", namespace = "") 
	 protected String compactName;
	@XmlElement(name = "CompactRevision", namespace = "") 
	 protected String compactRevision;
	@XmlElement(name = "CompactRole", namespace = "") 
	 protected String compactRole;
	public String getCompactType() {
		return compactType;
	}
	public void setCompactType(String compactType) {
		this.compactType = compactType;
	}
	public String getCompactName() {
		return compactName;
	}
	public void setCompactName(String compactName) {
		this.compactName = compactName;
	}
	public String getCompactRevision() {
		return compactRevision;
	}
	public void setCompactRevision(String compactRevision) {
		this.compactRevision = compactRevision;
	}
	public String getCompactRole() {
		return compactRole;
	}
	public void setCompactRole(String compactRole) {
		this.compactRole = compactRole;
	}

}
