//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"title",
		"description",
		"type",
		"formulationType",
		"formulationPropagate",
		"revision",
		"originated",
		"pdtemplatestopgPLISegmentName",
		"releasePhase",
		"owner",
		"releaseDate",
		"effectivityDate",
		"expirationDate",
		"previousRevisionObsoleteDate",
		"reasonforChange",
		"isProductCertificationorLocalStandardsComplianceStatementRequired",
		"productDoseperUse",
		"productDoseperUseUoM",
		"modeofProductDisposal",
		"expectedFrequencyofUse",
		"expectedFrequencyofUseUoM",
		"lifeCycleStatus",
		"specificationSubType",
		"pdtemplatestopgBrand",
		"productExtraVariant",
		"sclass",
		"subClass",
		"pdtemplatestopgPLIReportedFunction",
		"baseUnitOfMeasure",
		"isBattery",
		"containsBattery",
		"onshelfProductDensity",
		"densityUOM",
		"entryBaseQuantity",
		"bomBaseQuantity",
		"localDescription",
		"otherNames",
		"intendedMarkets",
		"replacedByProductID",
		"uniqueFormulaIdentifier",
		"comment",
		"archiveDate",
		"archiveComment",
		"pdtemplatestopgPLISegment",
		"coOwned",
		"modified"
})
@XmlRootElement(name = "Attributes", namespace = "")
public class Attributes2 {

			@XmlElement(name = "Title", namespace = "")
			protected String title;
			@XmlElement(name = "Description", namespace = "")
			protected String description;
			@XmlElement(name = "Type", namespace = "")
			protected String type;
			@XmlElement(name = "FormulationType", namespace = "")
			protected String formulationType;
			@XmlElement(name = "FormulationPropagate", namespace = "")
			protected String formulationPropagate;
			@XmlElement(name = "Revision", namespace = "")
			protected String revision;
			@XmlElement(name = "Originated", namespace = "")
			protected String originated;
			@XmlElement(name = "PDTemplatestopgPLISegmentName", namespace = "")
			protected String pdtemplatestopgPLISegmentName;
			@XmlElement(name = "ReleasePhase", namespace = "")
			protected String releasePhase;
			@XmlElement(name = "Owner", namespace = "")
			protected String owner;
			@XmlElement(name = "ReleaseDate", namespace = "")
			protected String releaseDate;
			@XmlElement(name = "EffectivityDate", namespace = "")
			protected String effectivityDate;
			@XmlElement(name = "ExpirationDate", namespace = "")
			protected String expirationDate;
			@XmlElement(name = "PreviousRevisionObsoleteDate", namespace = "")
			protected String previousRevisionObsoleteDate;
			@XmlElement(name = "ReasonforChange", namespace = "")
			protected String reasonforChange;
			@XmlElement(name = "IsProductCertificationorLocalStandardsComplianceStatementRequired", namespace = "")
			protected String isProductCertificationorLocalStandardsComplianceStatementRequired;
			@XmlElement(name = "ProductDoseperUse", namespace = "")
			protected String productDoseperUse;
			@XmlElement(name = "ProductDoseperUseUoM", namespace = "")
			protected String productDoseperUseUoM;
			@XmlElement(name = "ModeofProductDisposal", namespace = "")
			protected String modeofProductDisposal;
			@XmlElement(name = "ExpectedFrequencyofUse", namespace = "")
			protected String expectedFrequencyofUse;
			@XmlElement(name = "ExpectedFrequencyofUseUoM", namespace = "")
			protected String expectedFrequencyofUseUoM;
			@XmlElement(name = "LifeCycleStatus", namespace = "")
			protected String lifeCycleStatus;
			@XmlElement(name = "SpecificationSubType", namespace = "")
			protected String specificationSubType;
			@XmlElement(name = "PDTemplatestopgBrand", namespace = "")
			protected String pdtemplatestopgBrand;
			@XmlElement(name = "ProductExtraVariant", namespace = "")
			protected String productExtraVariant;
			@XmlElement(name = "Class", namespace = "")
			protected String sclass;
			@XmlElement(name = "SubClass", namespace = "")
			protected String subClass;
			@XmlElement(name = "PDTemplatestopgPLIReportedFunction", namespace = "")
			protected String pdtemplatestopgPLIReportedFunction;
			@XmlElement(name = "BaseUnitOfMeasure", namespace = "")
			protected String baseUnitOfMeasure;
			@XmlElement(name = "IsBattery", namespace = "")
			protected String isBattery;
			@XmlElement(name = "ContainsBattery", namespace = "")
			protected String containsBattery;
			@XmlElement(name = "OnshelfProductDensity", namespace = "")
			protected String onshelfProductDensity;
			@XmlElement(name = "DensityUOM", namespace = "")
			protected String densityUOM;
			@XmlElement(name = "EntryBaseQuantity", namespace = "")
			protected String entryBaseQuantity;
			@XmlElement(name = "BomBaseQuantity", namespace = "")
			protected String bomBaseQuantity;
			@XmlElement(name = "LocalDescription", namespace = "")
			protected String localDescription;
			@XmlElement(name = "OtherNames", namespace = "")
			protected String otherNames;
			@XmlElement(name = "IntendedMarkets", namespace = "")
			protected String intendedMarkets;
			@XmlElement(name = "ReplacedByProductID", namespace = "")
			protected String replacedByProductID;
			@XmlElement(name = "UniqueFormulaIdentifier", namespace = "")
			protected String uniqueFormulaIdentifier;
			@XmlElement(name = "Comment", namespace = "")
			protected String comment;
			@XmlElement(name = "ArchiveDate", namespace = "")
			protected String archiveDate;
			@XmlElement(name = "ArchiveComment", namespace = "")
			protected String archiveComment;
			@XmlElement(name = "PDTemplatestopgPLISegment", namespace = "")
			protected String pdtemplatestopgPLISegment;
			@XmlElement(name = "CoOwned", namespace = "")
			protected String coOwned;
			@XmlElement(name = "Modified", namespace = "")
			protected String modified;
    
			public String getTitle() {
				return title;
			}
			public void setTitle(String title) {
				this.title = title;
			}
			public String getDescription() {
				return description;
			}
			public void setDescription(String description) {
				this.description = description;
			}
			public String getType() {
				return type;
			}
			public void setType(String type) {
				this.type = type;
			}
			public String getFormulationType() {
				return formulationType;
			}
			public void setFormulationType(String formulationType) {
				this.formulationType = formulationType;
			}
			public String getFormulationPropagate() {
				return formulationPropagate;
			}
			public void setFormulationPropagate(String formulationPropagate) {
				this.formulationPropagate = formulationPropagate;
			}
			public String getRevision() {
				return revision;
			}
			public void setRevision(String revision) {
				this.revision = revision;
			}
			public String getOriginated() {
				return originated;
			}
			public void setOriginated(String originated) {
				this.originated = originated;
			}
			public String getPdtemplatestopgPLISegmentName() {
				return pdtemplatestopgPLISegmentName;
			}
			public void setPdtemplatestopgPLISegmentName(String pdtemplatestopgPLISegmentName) {
				this.pdtemplatestopgPLISegmentName = pdtemplatestopgPLISegmentName;
			}
			public String getReleasePhase() {
				return releasePhase;
			}
			public void setReleasePhase(String releasePhase) {
				this.releasePhase = releasePhase;
			}
			public String getOwner() {
				return owner;
			}
			public void setOwner(String owner) {
				this.owner = owner;
			}
			public String getReleaseDate() {
				return releaseDate;
			}
			public void setReleaseDate(String releaseDate) {
				this.releaseDate = releaseDate;
			}
			public String getEffectivityDate() {
				return effectivityDate;
			}
			public void setEffectivityDate(String effectivityDate) {
				this.effectivityDate = effectivityDate;
			}
			public String getExpirationDate() {
				return expirationDate;
			}
			public void setExpirationDate(String expirationDate) {
				this.expirationDate = expirationDate;
			}
			public String getPreviousRevisionObsoleteDate() {
				return previousRevisionObsoleteDate;
			}
			public void setPreviousRevisionObsoleteDate(String previousRevisionObsoleteDate) {
				this.previousRevisionObsoleteDate = previousRevisionObsoleteDate;
			}
			public String getReasonforChange() {
				return reasonforChange;
			}
			public void setReasonforChange(String reasonforChange) {
				this.reasonforChange = reasonforChange;
			}
			public String getIsProductCertificationorLocalStandardsComplianceStatementRequired() {
				return this.isProductCertificationorLocalStandardsComplianceStatementRequired;
			}
			public void setIsProductCertificationorLocalStandardsComplianceStatementRequired(
					String isProductCertificationorLocalStandardsComplianceStatementRequired) {
				this.isProductCertificationorLocalStandardsComplianceStatementRequired = isProductCertificationorLocalStandardsComplianceStatementRequired;
			}
			public String getProductDoseperUse() {
				return productDoseperUse;
			}
			public void setProductDoseperUse(String productDoseperUse) {
				this.productDoseperUse = productDoseperUse;
			}
			public String getProductDoseperUseUoM() {
				return productDoseperUseUoM;
			}
			public void setProductDoseperUseUoM(String productDoseperUseUoM) {
				this.productDoseperUseUoM = productDoseperUseUoM;
			}
			public String getModeofProductDisposal() {
				return modeofProductDisposal;
			}
			public void setModeofProductDisposal(String modeofProductDisposal) {
				this.modeofProductDisposal = modeofProductDisposal;
			}
			public String getExpectedFrequencyofUse() {
				return expectedFrequencyofUse;
			}
			public void setExpectedFrequencyofUse(String expectedFrequencyofUse) {
				this.expectedFrequencyofUse = expectedFrequencyofUse;
			}
			public String getExpectedFrequencyofUseUoM() {
				return expectedFrequencyofUseUoM;
			}
			public void setExpectedFrequencyofUseUoM(String expectedFrequencyofUseUoM) {
				this.expectedFrequencyofUseUoM = expectedFrequencyofUseUoM;
			}
			public String getLifeCycleStatus() {
				return lifeCycleStatus;
			}
			public void setLifeCycleStatus(String lifeCycleStatus) {
				this.lifeCycleStatus = lifeCycleStatus;
			}
			public String getSpecificationSubType() {
				return specificationSubType;
			}
			public void setSpecificationSubType(String specificationSubType) {
				this.specificationSubType = specificationSubType;
			}
			public String getPdtemplatestopgBrand() {
				return pdtemplatestopgBrand;
			}
			public void setPdtemplatestopgBrand(String pdtemplatestopgBrand) {
				this.pdtemplatestopgBrand = pdtemplatestopgBrand;
			}
			public String getProductExtraVariant() {
				return productExtraVariant;
			}
			public void setProductExtraVariant(String productExtraVariant) {
				this.productExtraVariant = productExtraVariant;
			}
			public String getSclass() {
				return sclass;
			}
			public void setSclass(String sclass) {
				this.sclass = sclass;
			}
			public String getSubClass() {
				return subClass;
			}
			public void setSubClass(String subClass) {
				this.subClass = subClass;
			}
			public String getPdtemplatestopgPLIReportedFunction() {
				return pdtemplatestopgPLIReportedFunction;
			}
			public void setPdtemplatestopgPLIReportedFunction(String pdtemplatestopgPLIReportedFunction) {
				this.pdtemplatestopgPLIReportedFunction = pdtemplatestopgPLIReportedFunction;
			}
			public String getBaseUnitOfMeasure() {
				return baseUnitOfMeasure;
			}
			public void setBaseUnitOfMeasure(String baseUnitOfMeasure) {
				this.baseUnitOfMeasure = baseUnitOfMeasure;
			}
			public String getIsBattery() {
				return isBattery;
			}
			public void setIsBattery(String isBattery) {
				this.isBattery = isBattery;
			}
			public String getContainsBattery() {
				return containsBattery;
			}
			public void setContainsBattery(String containsBattery) {
				this.containsBattery = containsBattery;
			}
			public String getOnshelfProductDensity() {
				return onshelfProductDensity;
			}
			public void setOnshelfProductDensity(String onshelfProductDensity) {
				this.onshelfProductDensity = onshelfProductDensity;
			}
			public String getDensityUOM() {
				return densityUOM;
			}
			public void setDensityUOM(String densityUOM) {
				this.densityUOM = densityUOM;
			}
			public String getEntryBaseQuantity() {
				return entryBaseQuantity;
			}
			public void setEntryBaseQuantity(String entryBaseQuantity) {
				this.entryBaseQuantity = entryBaseQuantity;
			}
			public String getBomBaseQuantity() {
				return bomBaseQuantity;
			}
			public void setBomBaseQuantity(String bomBaseQuantity) {
				this.bomBaseQuantity = bomBaseQuantity;
			}
			public String getLocalDescription() {
				return localDescription;
			}
			public void setLocalDescription(String localDescription) {
				this.localDescription = localDescription;
			}
			public String getOtherNames() {
				return otherNames;
			}
			public void setOtherNames(String otherNames) {
				this.otherNames = otherNames;
			}
			public String getIntendedMarkets() {
				return intendedMarkets;
			}
			public void setIntendedMarkets(String intendedMarkets) {
				this.intendedMarkets = intendedMarkets;
			}
			public String getReplacedByProductID() {
				return replacedByProductID;
			}
			public void setReplacedByProductID(String replacedByProductID) {
				this.replacedByProductID = replacedByProductID;
			}
			public String getUniqueFormulaIdentifier() {
				return uniqueFormulaIdentifier;
			}
			public void setUniqueFormulaIdentifier(String uniqueFormulaIdentifier) {
				this.uniqueFormulaIdentifier = uniqueFormulaIdentifier;
			}
			public String getComment() {
				return comment;
			}
			public void setComment(String comment) {
				this.comment = comment;
			}
			public String getArchiveDate() {
				return archiveDate;
			}
			public void setArchiveDate(String archiveDate) {
				this.archiveDate = archiveDate;
			}
			public String getArchiveComment() {
				return archiveComment;
			}
			public void setArchiveComment(String archiveComment) {
				this.archiveComment = archiveComment;
			}
			public String getPdtemplatestopgPLISegment() {
				return pdtemplatestopgPLISegment;
			}
			public void setPdtemplatestopgPLISegment(String pdtemplatestopgPLISegment) {
				this.pdtemplatestopgPLISegment = pdtemplatestopgPLISegment;
			}
			public String getCoOwned() {
				return coOwned;
			}
			public void setCoOwned(String coOwned) {
				this.coOwned = coOwned;
			}
			public String getModified() {
				return modified;
			}
			public void setModified(String modified) {
				this.modified = modified;
			}

}
