//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"title",
	"description",
	"type",
	"assemblyType",
	"revision",
	"originated",
	"releasePhase",
	"owner",
	"releaseDate",
	"effectivityDate",
	"expirationDate",
	"previousRevisionObsoleteDate",
	"keyAffectedImplemented",
	"lifeCycleStatus",
	"partFamilyName",
	"reasonforChange",
	"pDTemplatestopgBrand",
	"baseUnitOfMeasure",
	"wDStatius",
	"bOMBaseQuantity",
	"otherNames",
	"localDescription",
	"marketingSize",
	"pGCSU",
	"customizationType",
	"comment",
	"shippingInstructions",
	"labelingInformation",
	"storageInformation",
	"marketingName",
	"primaryPackagingType",
	"secondaryPackagingType",
	"packagingSize",
	"packagingSizeUOM",
	"archiveDate",
	"archiveComment",
	"iPClassification"

})
@XmlRootElement(name = "Attributes", namespace = "")
public class Attributes {

	@XmlElement(name = "Title", namespace = "") 
	 protected String title;
	@XmlElement(name = "Description", namespace = "") 
	 protected String description;
	@XmlElement(name = "type", namespace = "") 
	 protected String type;
	@XmlElement(name = "AssemblyType", namespace = "") 
	 protected String assemblyType;
	@XmlElement(name = "Revision", namespace = "") 
	 protected String revision;
	@XmlElement(name = "Originated", namespace = "") 
	 protected String originated;
	@XmlElement(name = "ReleasePhase", namespace = "") 
	 protected String releasePhase;
	@XmlElement(name = "Owner", namespace = "") 
	 protected String owner;
	@XmlElement(name = "ReleaseDate", namespace = "") 
	 protected String releaseDate;
	@XmlElement(name = "EffectivityDate", namespace = "") 
	 protected String effectivityDate;
	@XmlElement(name = "ExpirationDate", namespace = "") 
	 protected String expirationDate;
	
	@XmlElement(name = "PreviousRevisionObsoleteDate", namespace = "") 
	 protected String previousRevisionObsoleteDate;
	
	@XmlElement(name = "KeyAffectedImplemented", namespace = "") 
	 protected String keyAffectedImplemented;
	@XmlElement(name = "LifeCycleStatus", namespace = "") 
	 protected String lifeCycleStatus;
	@XmlElement(name = "PartFamilyName", namespace = "") 
	 protected String partFamilyName;
	@XmlElement(name = "ReasonforChange", namespace = "") 
	 protected String reasonforChange;
	@XmlElement(name = "PDTemplatestopgBrand", namespace = "") 
	 protected String pDTemplatestopgBrand;
	@XmlElement(name = "BaseUnitOfMeasure", namespace = "") 
	 protected String baseUnitOfMeasure;
	@XmlElement(name = "WDStatius", namespace = "") 
	 protected String wDStatius;
	@XmlElement(name = "BOMBaseQuantity", namespace = "") 
	 protected String bOMBaseQuantity;
	@XmlElement(name = "OtherNames", namespace = "") 
	 protected String otherNames;
	@XmlElement(name = "LocalDescription", namespace = "") 
	 protected String localDescription;
	@XmlElement(name = "MarketingSize", namespace = "") 
	 protected String marketingSize;
	@XmlElement(name = "PGCSU", namespace = "") 
	 protected String pGCSU;
	@XmlElement(name = "CustomizationType", namespace = "") 
	 protected String customizationType;
	@XmlElement(name = "Comment", namespace = "") 
	 protected String comment;
	@XmlElement(name = "ShippingInstructions", namespace = "") 
	 protected String shippingInstructions;
	@XmlElement(name = "LabelingInformation", namespace = "") 
	 protected String labelingInformation;
	@XmlElement(name = "StorageInformation", namespace = "") 
	 protected String storageInformation;
	@XmlElement(name = "MarketingName", namespace = "") 
	 protected String marketingName;
	@XmlElement(name = "PrimaryPackagingType", namespace = "") 
	 protected String primaryPackagingType;
	@XmlElement(name = "SecondaryPackagingType", namespace = "") 
	 protected String secondaryPackagingType;
	@XmlElement(name = "PackagingSize", namespace = "") 
	 protected String packagingSize;
	@XmlElement(name = "PackagingSizeUOM", namespace = "") 
	 protected String packagingSizeUOM;
	@XmlElement(name = "ArchiveDate", namespace = "") 
	 protected String archiveDate;
	@XmlElement(name = "ArchiveComment", namespace = "") 
	 protected String archiveComment;
	@XmlElement(name = "IPClassification", namespace = "") 
	 protected String iPClassification;
	
	public String getPreviousRevisionObsoleteDate() {
		return previousRevisionObsoleteDate;
	}
	public void setPreviousRevisionObsoleteDate(String previousRevisionObsoleteDate) {
		this.previousRevisionObsoleteDate = previousRevisionObsoleteDate;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getAssemblyType() {
		return assemblyType;
	}
	public void setAssemblyType(String assemblyType) {
		this.assemblyType = assemblyType;
	}
	public String getRevision() {
		return revision;
	}
	public void setRevision(String revision) {
		this.revision = revision;
	}
	public String getOriginated() {
		return originated;
	}
	public void setOriginated(String originated) {
		this.originated = originated;
	}
	public String getReleasePhase() {
		return releasePhase;
	}
	public void setReleasePhase(String releasePhase) {
		this.releasePhase = releasePhase;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getReleaseDate() {
		return releaseDate;
	}
	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}
	public String getEffectivityDate() {
		return effectivityDate;
	}
	public void setEffectivityDate(String effectivityDate) {
		this.effectivityDate = effectivityDate;
	}
	public String getExpirationDate() {
		return expirationDate;
	}
	public void setExpirationDate(String expirationDate) {
		this.expirationDate = expirationDate;
	}
	public String getKeyAffectedImplemented() {
		return keyAffectedImplemented;
	}
	public void setKeyAffectedImplemented(String keyAffectedImplemented) {
		this.keyAffectedImplemented = keyAffectedImplemented;
	}
	public String getLifeCycleStatus() {
		return lifeCycleStatus;
	}
	public void setLifeCycleStatus(String lifeCycleStatus) {
		this.lifeCycleStatus = lifeCycleStatus;
	}
	public String getPartFamilyName() {
		return partFamilyName;
	}
	public void setPartFamilyName(String partFamilyName) {
		this.partFamilyName = partFamilyName;
	}
	public String getReasonforChange() {
		return reasonforChange;
	}
	public void setReasonforChange(String reasonforChange) {
		this.reasonforChange = reasonforChange;
	}
	public String getpDTemplatestopgBrand() {
		return pDTemplatestopgBrand;
	}
	public void setpDTemplatestopgBrand(String pDTemplatestopgBrand) {
		this.pDTemplatestopgBrand = pDTemplatestopgBrand;
	}
	public String getBaseUnitOfMeasure() {
		return baseUnitOfMeasure;
	}
	public void setBaseUnitOfMeasure(String baseUnitOfMeasure) {
		this.baseUnitOfMeasure = baseUnitOfMeasure;
	}
	public String getwDStatius() {
		return wDStatius;
	}
	public void setwDStatius(String wDStatius) {
		this.wDStatius = wDStatius;
	}
	public String getbOMBaseQuantity() {
		return bOMBaseQuantity;
	}
	public void setbOMBaseQuantity(String bOMBaseQuantity) {
		this.bOMBaseQuantity = bOMBaseQuantity;
	}
	public String getOtherNames() {
		return otherNames;
	}
	public void setOtherNames(String otherNames) {
		this.otherNames = otherNames;
	}
	public String getLocalDescription() {
		return localDescription;
	}
	public void setLocalDescription(String localDescription) {
		this.localDescription = localDescription;
	}
	public String getMarketingSize() {
		return marketingSize;
	}
	public void setMarketingSize(String marketingSize) {
		this.marketingSize = marketingSize;
	}
	public String getpGCSU() {
		return pGCSU;
	}
	public void setpGCSU(String pGCSU) {
		this.pGCSU = pGCSU;
	}
	public String getCustomizationType() {
		return customizationType;
	}
	public void setCustomizationType(String customizationType) {
		this.customizationType = customizationType;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public String getShippingInstructions() {
		return shippingInstructions;
	}
	public void setShippingInstructions(String shippingInstructions) {
		this.shippingInstructions = shippingInstructions;
	}
	public String getLabelingInformation() {
		return labelingInformation;
	}
	public void setLabelingInformation(String labelingInformation) {
		this.labelingInformation = labelingInformation;
	}
	public String getStorageInformation() {
		return storageInformation;
	}
	public void setStorageInformation(String storageInformation) {
		this.storageInformation = storageInformation;
	}
	public String getMarketingName() {
		return marketingName;
	}
	public void setMarketingName(String marketingName) {
		this.marketingName = marketingName;
	}
	public String getPrimaryPackagingType() {
		return primaryPackagingType;
	}
	public void setPrimaryPackagingType(String primaryPackagingType) {
		this.primaryPackagingType = primaryPackagingType;
	}
	public String getSecondaryPackagingType() {
		return secondaryPackagingType;
	}
	public void setSecondaryPackagingType(String secondaryPackagingType) {
		this.secondaryPackagingType = secondaryPackagingType;
	}
	public String getPackagingSize() {
		return packagingSize;
	}
	public void setPackagingSize(String packagingSize) {
		this.packagingSize = packagingSize;
	}
	public String getPackagingSizeUOM() {
		return packagingSizeUOM;
	}
	public void setPackagingSizeUOM(String packagingSizeUOM) {
		this.packagingSizeUOM = packagingSizeUOM;
	}
	public String getArchiveDate() {
		return archiveDate;
	}
	public void setArchiveDate(String archiveDate) {
		this.archiveDate = archiveDate;
	}
	public String getArchiveComment() {
		return archiveComment;
	}
	public void setArchiveComment(String archiveComment) {
		this.archiveComment = archiveComment;
	}
	public String getiPClassification() {
		return iPClassification;
	}
	public void setiPClassification(String iPClassification) {
		this.iPClassification = iPClassification;
	}
	
	
	
	}
