//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.pdfview.impl.common.GenericModel;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributes",
    "organizations",
    "dgcs",
    "storageTransportationData",
    "warehouseClassification",
    "ghss","plants","ownership","packingUnits","uniqueFormulaIdentifiers",
    "weightsAndDimensions","notes","allBillOfMaterial","performanceCharacteristics",
    "certifications","referenceDocuments","relatedSpecifications",
    "relatedATS","lifeCycle","derivedParts","sapBOMAsFeds",
    "stabilityResults","securityClasses","countryOfSales","genericModel"
})
@XmlRootElement(name = "Basic", namespace = "")
public class Basic {

    @XmlElement(name = "Attributes", namespace = "")
    protected Attributes attributes;
    @XmlElement(name = "Organizations", namespace = "")
    protected Organizations organizations;
	@XmlElement(name = "Ghss", namespace = "")
	protected Ghss ghss;
	@XmlElement(name = "Dgcs", namespace = "")
	protected Dgcs dgcs;
	@XmlElement(name = "StorageTransportationData", namespace = "")
	protected StorageTransportationData storageTransportationData;
	@XmlElement(name = "WarehouseClassification", namespace = "")
	protected WarehouseClassification warehouseClassification;
	@XmlElement(name = "Plants", namespace = "")
	protected Plants plants;
	@XmlElement(name = "Ownership", namespace = "")
	protected Ownership ownership;
	@XmlElement(name = "PackingUnits", namespace = "")
	protected PackingUnits packingUnits;
	@XmlElement(name = "UniqueFormulaIdentifiers", namespace = "")
	protected UniqueFormulaIdentifiers uniqueFormulaIdentifiers;
	@XmlElement(name = "WeightsAndDimensions", namespace = "")
	protected WeightsAndDimensions weightsAndDimensions;
	@XmlElement(name = "Notes", namespace = "")
	protected Note notes;
	@XmlElement(name = "AllBillOfMaterial", namespace = "")
	protected AllBillOfMaterial allBillOfMaterial;
	@XmlElement(name = "PerformanceCharacteristics", namespace = "")
	protected PerformanceCharacteristics  performanceCharacteristics;
	@XmlElement(name = "Certifications", namespace = "")
	protected Certifications  certifications;
	@XmlElement(name = "ReferenceDocuments", namespace = "")
	protected ReferenceDocuments  referenceDocuments;
	@XmlElement(name = "RelatedSpecifications", namespace = "")
	protected RelatedSpecifications relatedSpecifications;
	@XmlElement(name = "RelatedATS", namespace = "")
	protected RelatedATS relatedATS;
	@XmlElement(name = "LifeCycle", namespace = "")
	protected LifeCycle lifeCycle;
	@XmlElement(name = "DerivedParts", namespace = "")
	protected DerivedParts derivedParts;
	@XmlElement(name = "SapBOMAsFeds", namespace = "")
	protected SapBOMAsFeds sapBOMAsFeds;
	@XmlElement(name = "StabilityResults", namespace = "")
	protected StabilityResults stabilityResults;
	@XmlElement(name = "SecurityClasses", namespace = "")
	protected SecurityClasses securityClasses;
	@XmlElement(name = "CountryOfSales", namespace = "")
	protected CountryOfSales countryOfSales;
	@XmlElement(name = "GenericModel", namespace = "")
	protected GenericModel genericModel;
	public WarehouseClassification getWarehouseClassification() {
		return warehouseClassification;
	}

	public void setWarehouseClassification(WarehouseClassification warehouseClassification) {
		this.warehouseClassification = warehouseClassification;
	}

	public StorageTransportationData getStorageTransportationData() {
		return storageTransportationData;
	}

	public void setStorageTransportationData(StorageTransportationData storageTransportationData) {
		this.storageTransportationData = storageTransportationData;
	}

	public Dgcs getDgcs() {
		return dgcs;
	}

	public void setDgcs(Dgcs dgcs) {
		this.dgcs = dgcs;
	}

	public Organizations getOrganizations() {
		return organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	public Ghss getGhss() {
		return ghss;
	}

	public void setGhss(Ghss ghss) {
		this.ghss = ghss;
	}

	public Attributes getAttributes() {
		return attributes;
	}

	public void setAttributes(Attributes attributes) {
		this.attributes = attributes;
	}
	public Plants getPlants() {
		return plants;
	}

	public void setPlants(Plants plants) {
		this.plants = plants;
	}
    
	public Ownership getOwnership() {
		return ownership;
	}

	public void setOwnership(Ownership ownership) {
		this.ownership = ownership;
	}

	public PackingUnits getPackingUnits() {
		return packingUnits;
	}

	public void setPackingUnits(PackingUnits packingUnits) {
		this.packingUnits = packingUnits;
	}

	public UniqueFormulaIdentifiers getUniqueFormulaIdentifiers() {
		return uniqueFormulaIdentifiers;
	}

	public void setUniqueFormulaIdentifiers(UniqueFormulaIdentifiers uniqueFormulaIdentifiers) {
		this.uniqueFormulaIdentifiers = uniqueFormulaIdentifiers;
	}

	public WeightsAndDimensions getWeightsAndDimensions() {
		return weightsAndDimensions;
	}

	public void setWeightsAndDimensions(WeightsAndDimensions weightsAndDimensions) {
		this.weightsAndDimensions = weightsAndDimensions;
	}

	public Note getNotes() {
		return notes;
	}

	public void setNotes(Note notes) {
		this.notes = notes;
	}

	public AllBillOfMaterial getAllBillOfMaterial() {
		return allBillOfMaterial;
	}

	public void setAllBillOfMaterial(AllBillOfMaterial allBillOfMaterial) {
		this.allBillOfMaterial = allBillOfMaterial;
	}

	public PerformanceCharacteristics getPerformanceCharacteristics() {
		return performanceCharacteristics;
	}

	public void setPerformanceCharacteristics(PerformanceCharacteristics performanceCharacteristics) {
		this.performanceCharacteristics = performanceCharacteristics;
	}

	public Certifications getCertifications() {
		return certifications;
	}

	public void setCertifications(Certifications certifications) {
		this.certifications = certifications;
	}

	public ReferenceDocuments getReferenceDocuments() {
		return referenceDocuments;
	}

	public void setReferenceDocuments(ReferenceDocuments referenceDocuments) {
		this.referenceDocuments = referenceDocuments;
	}

	public RelatedSpecifications getRelatedSpecifications() {
		return relatedSpecifications;
	}

	public void setRelatedSpecifications(RelatedSpecifications relatedSpecifications) {
		this.relatedSpecifications = relatedSpecifications;
	}

	public RelatedATS getRelatedATS() {
		return relatedATS;
	}

	public void setRelatedATS(RelatedATS relatedATS) {
		this.relatedATS = relatedATS;
	}

	public LifeCycle getLifeCycle() {
		return lifeCycle;
	}

	public void setLifeCycle(LifeCycle lifeCycle) {
		this.lifeCycle = lifeCycle;
	}


	public DerivedParts getDerivedParts() {
		return derivedParts;
	}

	public void setDerivedParts(DerivedParts derivedParts) {
		this.derivedParts = derivedParts;
	}

	public SapBOMAsFeds getSapBOMAsFeds() {
		return sapBOMAsFeds;
	}

	public void setSapBOMAsFeds(SapBOMAsFeds sapBOMAsFeds) {
		this.sapBOMAsFeds = sapBOMAsFeds;
	}

	public StabilityResults getStabilityResults() {
		return stabilityResults;
	}

	public void setStabilityResults(StabilityResults stabilityResults) {
		this.stabilityResults = stabilityResults;
	}

	public SecurityClasses getSecurityClasses() {
		return securityClasses;
	}

	public void setSecurityClasses(SecurityClasses securityClasses) {
		this.securityClasses = securityClasses;
	}

	public CountryOfSales getCountryOfSales() {
		return countryOfSales;
	}

	public void setCountryOfSales(CountryOfSales countryOfSales) {
		this.countryOfSales = countryOfSales;
	}

	public GenericModel getGenericModel() {
		return genericModel;
	}

	public void setGenericModel(GenericModel genericModel) {
		this.genericModel = genericModel;
	}
	
}
