//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//

package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
"name",
"chg",
"fN",
"title",
"type",
"substitution",
"qty",
"baseUnitofMeasure",
"comments",
"revision",
"releaseDate",
"state",
"phase",
"refDesOptional",
"components",
"certification",
"alternate",
"minimum",
"maximum",
"net",
"loss",
"netWeight",
"weightUoM",
"meterialFunction",
"onShelfProduct",
"densityUOM",
"policy"

})

public class BillofMaterial {
	@XmlElement(name = "Name", namespace = "") 
	 protected String name;
	@XmlElement(name = "Chg", namespace = "") 
	 protected String chg;
	@XmlElement(name = "FN", namespace = "") 
	 protected String fN;
	@XmlElement(name = "Certification", namespace = "") 
	 protected String certification; 
	
	@XmlElement(name = "Title", namespace = "") 
	 protected String title;
	@XmlElement(name = "Type", namespace = "") 
	 protected String type;
	@XmlElement(name = "Substitution", namespace = "") 
	 protected String substitution;
	@XmlElement(name = "Qty", namespace = "") 
	 protected String qty;
	@XmlElement(name = "BaseUnitofMeasure", namespace = "") 
	 protected String baseUnitofMeasure;
	@XmlElement(name = "Comments", namespace = "") 
	 protected String comments;
	@XmlElement(name = "State", namespace = "") 
	 protected String state;
	@XmlElement(name = "Phase", namespace = "") 
	 protected String phase;
	@XmlElement(name = "RefDesOptional", namespace = "") 
	 protected String refDesOptional;
	@XmlElement(name = "Components", namespace = "") 
	 protected String components;	
	@XmlElement(name = "Revision", namespace = "") 
	 protected String revision;	
	@XmlElement(name = "ReleaseDate", namespace = "") 
	 protected String releaseDate;
	
	@XmlElement(name = "Alternate", namespace = "") 
	 protected String alternate;
	@XmlElement(name = "Minimum", namespace = "") 
	 protected String minimum;
	@XmlElement(name = "Maximum", namespace = "") 
	 protected String maximum;
	@XmlElement(name = "Net", namespace = "") 
	 protected String net;
	@XmlElement(name = "Loss", namespace = "") 
	 protected String loss;
	@XmlElement(name = "NetWeight", namespace = "") 
	 protected String netWeight;
	@XmlElement(name = "WeightUoM", namespace = "") 
	 protected String weightUoM;
	@XmlElement(name = "MeterialFunction", namespace = "") 
	 protected String meterialFunction;
	@XmlElement(name = "OnShelfProduct", namespace = "") 
	 protected String onShelfProduct;
	@XmlElement(name = "DensityUOM", namespace = "") 
	 protected String densityUOM;
	@XmlElement(name = "Policy", namespace = "") 
	 protected String policy;
	
	
	public String getRevision() {
		return revision;
	}
	public void setRevision(String revision) {
		this.revision = revision;
	}
	public String getReleaseDate() {
		return releaseDate;
	}
	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getChg() {
		return chg;
	}
	public void setChg(String chg) {
		this.chg = chg;
	}
	public String getfN() {
		return fN;
	}
	public void setfN(String fN) {
		this.fN = fN;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getSubstitution() {
		return substitution;
	}
	public void setSubstitution(String substitution) {
		this.substitution = substitution;
	}
	public String getQty() {
		return qty;
	}
	public void setQty(String qty) {
		this.qty = qty;
	}
	public String getBaseUnitofMeasure() {
		return baseUnitofMeasure;
	}
	public void setBaseUnitofMeasure(String baseUnitofMeasure) {
		this.baseUnitofMeasure = baseUnitofMeasure;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getPhase() {
		return phase;
	}
	public void setPhase(String phase) {
		this.phase = phase;
	}
	public String getRefDesOptional() {
		return refDesOptional;
	}
	public void setRefDesOptional(String refDesOptional) {
		this.refDesOptional = refDesOptional;
	}
	public String getComponents() {
		return components;
	}
	public void setComponents(String components) {
		this.components = components;
	}
	public String getCertification() {
		return certification;
	}
	public void setCertification(String certification) {
		this.certification = certification;
	}
	public String getAlternate() {
		return alternate;
	}
	public void setAlternate(String alternate) {
		this.alternate = alternate;
	}
	public String getMinimum() {
		return minimum;
	}
	public void setMinimum(String minimum) {
		this.minimum = minimum;
	}
	public String getMaximum() {
		return maximum;
	}
	public void setMaximum(String maximum) {
		this.maximum = maximum;
	}
	public String getNet() {
		return net;
	}
	public void setNet(String net) {
		this.net = net;
	}
	public String getLoss() {
		return loss;
	}
	public void setLoss(String loss) {
		this.loss = loss;
	}
	public String getNetWeight() {
		return netWeight;
	}
	public void setNetWeight(String netWeight) {
		this.netWeight = netWeight;
	}
	public String getWeightUoM() {
		return weightUoM;
	}
	public void setWeightUoM(String weightUoM) {
		this.weightUoM = weightUoM;
	}
	public String getMeterialFunction() {
		return meterialFunction;
	}
	public void setMeterialFunction(String meterialFunction) {
		this.meterialFunction = meterialFunction;
	}
	public String getOnShelfProduct() {
		return onShelfProduct;
	}
	public void setOnShelfProduct(String onShelfProduct) {
		this.onShelfProduct = onShelfProduct;
	}
	public String getDensityUOM() {
		return densityUOM;
	}
	public void setDensityUOM(String densityUOM) {
		this.densityUOM = densityUOM;
	}
	public String getPolicy() {
		return policy;
	}
	public void setPolicy(String policy) {
		this.policy = policy;
	}
	
}
