package com.pdfview.impl.FPP;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "classificationPowerView","headerName"
})
@XmlRootElement(name = "ClassificationPowerViews", namespace = "")
public class ClassificationPowerViews {

 @XmlElement(name = "classificationPowerView", namespace = "")
 protected List<ClassificationPowerView> classificationPowerView;


public void setClassificationPowerView(List<ClassificationPowerView> classificationPowerView) {
	this.classificationPowerView = classificationPowerView;
}
/**
  * Gets the value of the rule property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the rule property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getRule().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link Ghs }
  * 
  * 
  */

public List<ClassificationPowerView> getClassificationPowerView() {
	 if (classificationPowerView == null) {
		 classificationPowerView = new ArrayList<ClassificationPowerView>();
     }
     return this.classificationPowerView;
}
 

}
