//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"countryname",
		"iscountryrestricted"
})
public class CountryOfSale {
	
	@XmlElement(name = "CountryName", namespace = "") 
	 protected String countryname;
	@XmlElement(name = "IsCountryRestricted", namespace = "") 
	 protected String iscountryrestricted;

	public String getCountryname() {
		return countryname;
	}
	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}
	public String getIscountryrestricted() {
		return iscountryrestricted;
	}
	public void setIscountryrestricted(String iscountryrestricted) {
		this.iscountryrestricted = iscountryrestricted;
	}
	
	
	
	
	

	
}
