//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"countryOfSale","lastcosdatetime"
	})
@XmlRootElement(name = "CountryOfSales", namespace = "")
public class CountryOfSales {
	@XmlElement(name = "LastCOSDateTime", namespace = "") 
	 protected String lastcosdatetime;
	@XmlElement(name = "CountryOfSale", namespace = "") 
	 protected List<CountryOfSale> countryOfSale;

	public List<CountryOfSale> getCountryOfSale() {
    	 if(countryOfSale == null) {
    		 countryOfSale = new ArrayList<CountryOfSale>();
         }
         return this.countryOfSale;
	}

	public String getLastcosdatetime() {
		return lastcosdatetime;
	}

	public void setLastcosdatetime(String lastcosdatetime) {
		this.lastcosdatetime = lastcosdatetime;
	}

	public void setCountryOfSale(List<CountryOfSale> countryOfSale) {
		this.countryOfSale = countryOfSale;
	}
	
}
