//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"toSourceName","toDerivedName","toDerivedDescription","toDerivedPartState","toDerivedPartSecurityCategory",
		"toSourcePartRevision","toGenerationNumber","toCreator","toCreateDate"

})
public class DerivedToPartsData {
	
	//ToDerived
	@XmlElement(name = "ToSourceName", namespace = "") 
	 protected String toSourceName;
	@XmlElement(name = "ToDerivedName", namespace = "") 
	 protected String toDerivedName;
	@XmlElement(name = "ToDerivedDescription", namespace = "") 
	 protected String toDerivedDescription;
	@XmlElement(name = "ToDerivedPartState", namespace = "") 
	 protected String toDerivedPartState;
	@XmlElement(name = "ToDerivedPartSecurityCategory", namespace = "") 
	 protected String toDerivedPartSecurityCategory;
	@XmlElement(name = "ToSourcePartRevision", namespace = "") 
	 protected String toSourcePartRevision;
	@XmlElement(name = "ToGenerationNumber", namespace = "") 
	 protected String toGenerationNumber;
	@XmlElement(name = "ToCreator", namespace = "") 
	 protected String toCreator;
	@XmlElement(name = "ToCreateDate", namespace = "") 
	 protected String toCreateDate;

	public String getToSourceName() {
		return toSourceName;
	}
	public void setToSourceName(String toSourceName) {
		this.toSourceName = toSourceName;
	}
	public String getToDerivedName() {
		return toDerivedName;
	}
	public void setToDerivedName(String toDerivedName) {
		this.toDerivedName = toDerivedName;
	}
	public String getToDerivedDescription() {
		return toDerivedDescription;
	}
	public void setToDerivedDescription(String toDerivedDescription) {
		this.toDerivedDescription = toDerivedDescription;
	}
	public String getToDerivedPartState() {
		return toDerivedPartState;
	}
	public void setToDerivedPartState(String toDerivedPartState) {
		this.toDerivedPartState = toDerivedPartState;
	}
	public String getToDerivedPartSecurityCategory() {
		return toDerivedPartSecurityCategory;
	}
	public void setToDerivedPartSecurityCategory(String toDerivedPartSecurityCategory) {
		this.toDerivedPartSecurityCategory = toDerivedPartSecurityCategory;
	}
	public String getToSourcePartRevision() {
		return toSourcePartRevision;
	}
	public void setToSourcePartRevision(String toSourcePartRevision) {
		this.toSourcePartRevision = toSourcePartRevision;
	}
	public String getToGenerationNumber() {
		return toGenerationNumber;
	}
	public void setToGenerationNumber(String toGenerationNumber) {
		this.toGenerationNumber = toGenerationNumber;
	}
	public String getToCreator() {
		return toCreator;
	}
	public void setToCreator(String toCreator) {
		this.toCreator = toCreator;
	}
	public String getToCreateDate() {
		return toCreateDate;
	}
	public void setToCreateDate(String toCreateDate) {
		this.toCreateDate = toCreateDate;
	}		
}
