//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"fromSourceName","fromDerivedName","fromDerivedDescription","fromDerivedPartState","fromDerivedPartSecurityCategory",
		"fromSourcePartRevision","fromGenerationNumber","fromCreator","fromCreateDate"
})
public class DerivedFromPartsData {
	//FromDerived
	@XmlElement(name = "FromSourceName", namespace = "") 
	 protected String fromSourceName;
	@XmlElement(name = "FromDerivedName", namespace = "") 
	 protected String fromDerivedName;
	@XmlElement(name = "FromDerivedDescription", namespace = "") 
	 protected String fromDerivedDescription;
	@XmlElement(name = "FromDerivedPartState", namespace = "") 
	 protected String fromDerivedPartState;
	@XmlElement(name = "FromDerivedPartSecurityCategory", namespace = "") 
	 protected String fromDerivedPartSecurityCategory;
	@XmlElement(name = "FromSourcePartRevision", namespace = "") 
	 protected String fromSourcePartRevision;
	@XmlElement(name = "FromGenerationNumber", namespace = "") 
	 protected String fromGenerationNumber;
	@XmlElement(name = "FromCreator", namespace = "") 
	 protected String fromCreator;
	@XmlElement(name = "FromCreateDate", namespace = "") 
	 protected String fromCreateDate;
	
	public String getFromSourceName() {
		return fromSourceName;
	}
	public void setFromSourceName(String fromSourceName) {
		this.fromSourceName = fromSourceName;
	}
	public String getFromDerivedName() {
		return fromDerivedName;
	}
	public void setFromDerivedName(String fromDerivedName) {
		this.fromDerivedName = fromDerivedName;
	}
	public String getFromDerivedDescription() {
		return fromDerivedDescription;
	}
	public void setFromDerivedDescription(String fromDerivedDescription) {
		this.fromDerivedDescription = fromDerivedDescription;
	}
	public String getFromDerivedPartState() {
		return fromDerivedPartState;
	}
	public void setFromDerivedPartState(String fromDerivedPartState) {
		this.fromDerivedPartState = fromDerivedPartState;
	}
	public String getFromDerivedPartSecurityCategory() {
		return fromDerivedPartSecurityCategory;
	}
	public void setFromDerivedPartSecurityCategory(String fromDerivedPartSecurityCategory) {
		this.fromDerivedPartSecurityCategory = fromDerivedPartSecurityCategory;
	}
	public String getFromSourcePartRevision() {
		return fromSourcePartRevision;
	}
	public void setFromSourcePartRevision(String fromSourcePartRevision) {
		this.fromSourcePartRevision = fromSourcePartRevision;
	}
	public String getFromGenerationNumber() {
		return fromGenerationNumber;
	}
	public void setFromGenerationNumber(String fromGenerationNumber) {
		this.fromGenerationNumber = fromGenerationNumber;
	}
	public String getFromCreator() {
		return fromCreator;
	}
	public void setFromCreator(String fromCreator) {
		this.fromCreator = fromCreator;
	}
	public String getFromCreateDate() {
		return fromCreateDate;
	}
	public void setFromCreateDate(String fromCreateDate) {
		this.fromCreateDate = fromCreateDate;
	}
		
}
