//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"name",
"ppn",
"ppr",
"ppt",
"title",
"rev",
"desc",
"state",
"countries",
"languagues"
})
public class Ghs {

	@XmlElement(name = "Name", namespace = "") 
	 protected String name;
	@XmlElement(name = "Ppn", namespace = "") 
	 protected String ppn;
	@XmlElement(name = "Ppr", namespace = "") 
	 protected String ppr;
	@XmlElement(name = "Ppt", namespace = "") 
	 protected String ppt;
	@XmlElement(name = "Title", namespace = "") 
	 protected String title;
	@XmlElement(name = "Rev", namespace = "") 
	 protected String rev;
	@XmlElement(name = "Desc", namespace = "") 
	 protected String desc;
	@XmlElement(name = "State", namespace = "") 
	 protected String state;
	@XmlElement(name = "Countries", namespace = "") 
	 protected String countries;
	@XmlElement(name = "Languagues", namespace = "") 
	 protected String languagues;
   
	public String getPpn() {
		return ppn;
	}
	public void setPpn(String ppn) {
		this.ppn = ppn;
	}
	public String getPpr() {
		return ppr;
	}
	public void setPpr(String ppr) {
		this.ppr = ppr;
	}
	public String getPpt() {
		return ppt;
	}
	public void setPpt(String ppt) {
		this.ppt = ppt;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getRev() {
		return rev;
	}
	public void setRev(String rev) {
		this.rev = rev;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getCountries() {
		return countries;
	}
	public void setCountries(String countries) {
		this.countries = countries;
	}
	public String getLanguagues() {
		return languagues;
	}
	public void setLanguagues(String languagues) {
		this.languagues = languagues;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
   
}
