//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"name","approver","title","approvalStatus","approvalDate","commentsOrInstructions","relatedObjects"

})
public class LifeCycleData {
	@XmlElement(name = "Name", namespace = "") 
	 protected String name;
	@XmlElement(name = "Approver", namespace = "") 
	 protected String approver;
	@XmlElement(name = "Title", namespace = "") 
	 protected String title;
	@XmlElement(name = "ApprovalStatus", namespace = "") 
	 protected String approvalStatus;
	@XmlElement(name = "ApprovalDate", namespace = "") 
	 protected String approvalDate;
	@XmlElement(name = "CommentsOrInstructions", namespace = "") 
	 protected String commentsOrInstructions;
	@XmlElement(name = "RelatedObjects", namespace = "") 
	 protected String relatedObjects;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getApprover() {
		return approver;
	}
	public void setApprover(String approver) {
		this.approver = approver;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getApprovalStatus() {
		return approvalStatus;
	}
	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus;
	}
	public String getApprovalDate() {
		return approvalDate;
	}
	public void setApprovalDate(String approvalDate) {
		this.approvalDate = approvalDate;
	}
	public String getCommentsOrInstructions() {
		return commentsOrInstructions;
	}
	public void setCommentsOrInstructions(String commentsOrInstructions) {
		this.commentsOrInstructions = commentsOrInstructions;
	}
	public String getRelatedObjects() {
		return relatedObjects;
	}
	public void setRelatedObjects(String relatedObjects) {
		this.relatedObjects = relatedObjects;
	}
	
	
		
}
