//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//

package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { 
	"primaryOrganization", 
	"secondaryOrganization"
})
@XmlRootElement(name = "Organizations", namespace = "")
public class Organizations {

	@XmlElement(name = "PrimaryOrganization", namespace = "")
	protected String primaryOrganization;
	@XmlElement(name = "SecondaryOrganization", namespace = "")
	protected String secondaryOrganization;

	public String getPrimaryOrganization() {
		return primaryOrganization;
	}

	public void setPrimaryOrganization(String primaryOrganization) {
		this.primaryOrganization = primaryOrganization;
	}

	public String getSecondaryOrganization() {
		return secondaryOrganization;
	}

	public void setSecondaryOrganization(String secondaryOrganization) {
		this.secondaryOrganization = secondaryOrganization;
	}

}
