//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Policy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Originator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Created" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Modified" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LeftExpressions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LeftExpression" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.pg.com/Rules_v1}Feature" minOccurs="0"/>
 *                             &lt;element ref="{http://www.pg.com/Rules_v1}Option" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Compatibility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RightExpressions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RightExpression" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.pg.com/Rules_v1}Feature" minOccurs="0"/>
 *                             &lt;element ref="{http://www.pg.com/Rules_v1}Option" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"packingUnitType",
		"aUOM",
		"gTIN",
		"depth",
		"width",
		"height",
		"dimensionUnitofMeasure",
		"grossWeight",
		"unitofMeasure",
		"numberofConsumerUnitsperUnit",
		"netWeightofProductinConsumerUnit"

})
public class PackingUnit {

	@XmlElement(name = "PackingUnitType", namespace = "") 
	 protected String packingUnitType;
	@XmlElement(name = "AUOM", namespace = "") 
	 protected String aUOM;
	@XmlElement(name = "GTIN", namespace = "") 
	 protected String gTIN;
	@XmlElement(name = "Depth", namespace = "") 
	 protected String depth;
	@XmlElement(name = "Width", namespace = "") 
	 protected String width;
	@XmlElement(name = "Height", namespace = "") 
	 protected String height;
	@XmlElement(name = "DimensionUnitofMeasure", namespace = "") 
	 protected String dimensionUnitofMeasure;
	@XmlElement(name = "UnitofMeasure", namespace = "") 
	 protected String unitofMeasure;
	@XmlElement(name = "NumberofConsumerUnitsperUnit", namespace = "") 
	 protected String numberofConsumerUnitsperUnit;
	@XmlElement(name = "NetWeightofProductinConsumerUnit", namespace = "") 
	 protected String netWeightofProductinConsumerUnit;
	@XmlElement(name = "GrossWeight", namespace = "") 
	protected String  grossWeight;

	public String getGrossWeight() {
		return grossWeight;
	}
	public void setGrossWeight(String grossWeight) {
		this.grossWeight = grossWeight;
	}
	public String getPackingUnitType() {
		return packingUnitType;
	}
	public void setPackingUnitType(String packingUnitType) {
		this.packingUnitType = packingUnitType;
	}
	public String getaUOM() {
		return aUOM;
	}
	public void setaUOM(String aUOM) {
		this.aUOM = aUOM;
	}
	public String getgTIN() {
		return gTIN;
	}
	public void setgTIN(String gTIN) {
		this.gTIN = gTIN;
	}
	public String getDepth() {
		return depth;
	}
	public void setDepth(String depth) {
		this.depth = depth;
	}
	public String getWidth() {
		return width;
	}
	public void setWidth(String width) {
		this.width = width;
	}
	public String getHeight() {
		return height;
	}
	public void setHeight(String height) {
		this.height = height;
	}
	public String getDimensionUnitofMeasure() {
		return dimensionUnitofMeasure;
	}
	public void setDimensionUnitofMeasure(String dimensionUnitofMeasure) {
		this.dimensionUnitofMeasure = dimensionUnitofMeasure;
	}
	public String getUnitofMeasure() {
		return unitofMeasure;
	}
	public void setUnitofMeasure(String unitofMeasure) {
		this.unitofMeasure = unitofMeasure;
	}
	public String getNumberofConsumerUnitsperUnit() {
		return numberofConsumerUnitsperUnit;
	}
	public void setNumberofConsumerUnitsperUnit(String numberofConsumerUnitsperUnit) {
		this.numberofConsumerUnitsperUnit = numberofConsumerUnitsperUnit;
	}
	public String getNetWeightofProductinConsumerUnit() {
		return netWeightofProductinConsumerUnit;
	}
	public void setNetWeightofProductinConsumerUnit(String netWeightofProductinConsumerUnit) {
		this.netWeightofProductinConsumerUnit = netWeightofProductinConsumerUnit;
	}
	
	
}
