//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"chg", "characteristics","characteristicSpecifics","path","testMethod","testMethodLogic","origin","otherTestMethodNumber",
		"testMethodSpecifics", "referenceDocument","sampling","subgroup","plantTestingLevel","plantTestingRetesting",
		"unitOfMeasureResting","lowerSpecLimit", "lowerRoutineReleaseLimit", "lowerTarget", "target", "upperTarget",
		"upperRoutineReleaseLimit", "upperSpecLimit","UOM","reportToNearest","reportType","releaseCriteria",
		"actionRequired","criticalityFactor","basis","testGroup","application"
})
public class PerformanceCharacteristic {
	@XmlElement(name = "Chg", namespace = "") 
	 protected String chg;
	@XmlElement(name = "Characteristics", namespace = "") 
	 protected String characteristics;
	@XmlElement(name = "CharacteristicSpecifics", namespace = "") 
	 protected String characteristicSpecifics;
	@XmlElement(name = "Path", namespace = "") 
	 protected String path;
	@XmlElement(name = "TestMethod", namespace = "") 
	 protected String testMethod;
	@XmlElement(name = "TestMethodLogic", namespace = "") 
	 protected String testMethodLogic;
	@XmlElement(name = "Origin", namespace = "") 
	 protected String origin;
	@XmlElement(name = "OtherTestMethodNumber", namespace = "") 
	 protected String otherTestMethodNumber;
	@XmlElement(name = "TestMethodSpecifics", namespace = "") 
	 protected String testMethodSpecifics;
	@XmlElement(name = "ReferenceDocument", namespace = "") 
	 protected String referenceDocument;
	@XmlElement(name = "Sampling", namespace = "") 
	 protected String sampling;
	@XmlElement(name = "Subgroup", namespace = "") 
	 protected String subgroup;
	@XmlElement(name = "PlantTestingLevel", namespace = "") 
	 protected String plantTestingLevel;
	@XmlElement(name = "PlantTestingRetesting", namespace = "") 
	 protected String plantTestingRetesting;
	@XmlElement(name = "UnitOfMeasureResting", namespace = "") 
	 protected String unitOfMeasureResting;
	@XmlElement(name = "LowerSpecLimit", namespace = "") 
	 protected String lowerSpecLimit;
	@XmlElement(name = "LowerRoutineReleaseLimit", namespace = "") 
	 protected String lowerRoutineReleaseLimit;
	@XmlElement(name = "LowerTarget", namespace = "") 
	 protected String lowerTarget;
	@XmlElement(name = "Target", namespace = "") 
	 protected String target;
	@XmlElement(name = "UpperTarget", namespace = "") 
	 protected String upperTarget;	
	@XmlElement(name = "UpperRoutineReleaseLimit", namespace = "") 
	 protected String upperRoutineReleaseLimit;
	@XmlElement(name = "UpperSpecLimit", namespace = "") 
	 protected String upperSpecLimit;
	@XmlElement(name = "UOM", namespace = "") 
	 protected String UOM;
	@XmlElement(name = "ReportToNearest", namespace = "") 
	 protected String reportToNearest;
	@XmlElement(name = "ReportType", namespace = "") 
	 protected String reportType;
	@XmlElement(name = "ReleaseCriteria", namespace = "") 
	 protected String releaseCriteria;	
	@XmlElement(name = "ActionRequired", namespace = "") 
	 protected String actionRequired;
	@XmlElement(name = "CriticalityFactor", namespace = "") 
	 protected String criticalityFactor;
	@XmlElement(name = "Basis", namespace = "") 
	 protected String basis;
	@XmlElement(name = "TestGroup", namespace = "") 
	 protected String testGroup;
	@XmlElement(name = "Application", namespace = "") 
	 protected String application;
	
	public String getChg() {
		return chg;
	}
	public void setChg(String chg) {
		this.chg = chg;
	}
	public String getCharacteristics() {
		return characteristics;
	}
	public void setCharacteristics(String characteristics) {
		this.characteristics = characteristics;
	}
	public String getCharacteristicSpecifics() {
		return characteristicSpecifics;
	}
	public void setCharacteristicSpecifics(String characteristicSpecifics) {
		this.characteristicSpecifics = characteristicSpecifics;
	}
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	public String getTestMethod() {
		return testMethod;
	}
	public void setTestMethod(String testMethod) {
		this.testMethod = testMethod;
	}
	public String getTestMethodLogic() {
		return testMethodLogic;
	}
	public void setTestMethodLogic(String testMethodLogic) {
		this.testMethodLogic = testMethodLogic;
	}
	public String getOrigin() {
		return origin;
	}
	public void setOrigin(String origin) {
		this.origin = origin;
	}
	public String getOtherTestMethodNumber() {
		return otherTestMethodNumber;
	}
	public void setOtherTestMethodNumber(String otherTestMethodNumber) {
		this.otherTestMethodNumber = otherTestMethodNumber;
	}
	public String getTestMethodSpecifics() {
		return testMethodSpecifics;
	}
	public void setTestMethodSpecifics(String testMethodSpecifics) {
		this.testMethodSpecifics = testMethodSpecifics;
	}
	public String getReferenceDocument() {
		return referenceDocument;
	}
	public void setReferenceDocument(String referenceDocument) {
		this.referenceDocument = referenceDocument;
	}
	public String getSampling() {
		return sampling;
	}
	public void setSampling(String sampling) {
		this.sampling = sampling;
	}
	public String getSubgroup() {
		return subgroup;
	}
	public void setSubgroup(String subgroup) {
		this.subgroup = subgroup;
	}
	public String getPlantTestingLevel() {
		return plantTestingLevel;
	}
	public void setPlantTestingLevel(String plantTestingLevel) {
		this.plantTestingLevel = plantTestingLevel;
	}
	public String getPlantTestingRetesting() {
		return plantTestingRetesting;
	}
	public void setPlantTestingRetesting(String plantTestingRetesting) {
		this.plantTestingRetesting = plantTestingRetesting;
	}
	public String getUnitOfMeasureResting() {
		return unitOfMeasureResting;
	}
	public void setUnitOfMeasureResting(String unitOfMeasureResting) {
		this.unitOfMeasureResting = unitOfMeasureResting;
	}
	public String getLowerSpecLimit() {
		return lowerSpecLimit;
	}
	public void setLowerSpecLimit(String lowerSpecLimit) {
		this.lowerSpecLimit = lowerSpecLimit;
	}
	public String getLowerRoutineReleaseLimit() {
		return lowerRoutineReleaseLimit;
	}
	public void setLowerRoutineReleaseLimit(String lowerRoutineReleaseLimit) {
		this.lowerRoutineReleaseLimit = lowerRoutineReleaseLimit;
	}
	public String getLowerTarget() {
		return lowerTarget;
	}
	public void setLowerTarget(String lowerTarget) {
		this.lowerTarget = lowerTarget;
	}
	public String getTarget() {
		return target;
	}
	public void setTarget(String target) {
		this.target = target;
	}
	public String getUpperTarget() {
		return upperTarget;
	}
	public void setUpperTarget(String upperTarget) {
		this.upperTarget = upperTarget;
	}
	public String getUpperRoutineReleaseLimit() {
		return upperRoutineReleaseLimit;
	}
	public void setUpperRoutineReleaseLimit(String upperRoutineReleaseLimit) {
		this.upperRoutineReleaseLimit = upperRoutineReleaseLimit;
	}
	public String getUpperSpecLimit() {
		return upperSpecLimit;
	}
	public void setUpperSpecLimit(String upperSpecLimit) {
		this.upperSpecLimit = upperSpecLimit;
	}
	public String getUOM() {
		return UOM;
	}
	public void setUOM(String uOM) {
		UOM = uOM;
	}
	public String getReportToNearest() {
		return reportToNearest;
	}
	public void setReportToNearest(String reportToNearest) {
		this.reportToNearest = reportToNearest;
	}
	public String getReportType() {
		return reportType;
	}
	public void setReportType(String reportType) {
		this.reportType = reportType;
	}
	public String getReleaseCriteria() {
		return releaseCriteria;
	}
	public void setReleaseCriteria(String releaseCriteria) {
		this.releaseCriteria = releaseCriteria;
	}
	public String getActionRequired() {
		return actionRequired;
	}
	public void setActionRequired(String actionRequired) {
		this.actionRequired = actionRequired;
	}
	public String getCriticalityFactor() {
		return criticalityFactor;
	}
	public void setCriticalityFactor(String criticalityFactor) {
		this.criticalityFactor = criticalityFactor;
	}
	public String getBasis() {
		return basis;
	}
	public void setBasis(String basis) {
		this.basis = basis;
	}
	public String getTestGroup() {
		return testGroup;
	}
	public void setTestGroup(String testGroup) {
		this.testGroup = testGroup;
	}
	public String getApplication() {
		return application;
	}
	public void setApplication(String application) {
		this.application = application;
	}
		
	
}
