//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"plantss",
		"plantsAuthorizedToUse",
		"plantsAuthorizedtoProduce",
		"activated",
		"authorizedactivated"

})
public class Plant {
	@XmlElement(name = "plantss", namespace = "") 
	 protected String plantss;
	@XmlElement(name = "plantsAuthorizedToUse", namespace = "") 
	 protected String plantsAuthorizedToUse;
	@XmlElement(name = "plantsAuthorizedtoProduce", namespace = "") 
	 protected String plantsAuthorizedtoProduce;
	@XmlElement(name = "activated", namespace = "") 
	 protected String activated;
	@XmlElement(name = "authorizedactivated", namespace = "") 
	 protected String authorizedactivated;
	
	public String getPlantss() {
		return plantss;
	}
	public void setPlantss(String plantss) {
		this.plantss = plantss;
	}
	public String getPlantsAuthorizedToUse() {
		return plantsAuthorizedToUse;
	}
	public void setPlantsAuthorizedToUse(String plantsAuthorizedToUse) {
		this.plantsAuthorizedToUse = plantsAuthorizedToUse;
	}
	public String getPlantsAuthorizedtoProduce() {
		return plantsAuthorizedtoProduce;
	}
	public void setPlantsAuthorizedtoProduce(String plantsAuthorizedtoProduce) {
		this.plantsAuthorizedtoProduce = plantsAuthorizedtoProduce;
	}
	public String getActivated() {
		return activated;
	}
	public void setActivated(String activated) {
		this.activated = activated;
	}
	public String getAuthorizedactivated() {
		return authorizedactivated;
	}
	public void setAuthorizedactivated(String authorizedactivated) {
		this.authorizedactivated = authorizedactivated;
	}
	
}
