//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//

package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
"name",
"sapdescription",
"type",
"specSub",
"sapType",
"subAltGroup",
"bomQuantity",
"uom",
"optionalcomponent",
"transportPart",
"comments",
"authorized",
"authorizedUse",
"authorizedProduce"
})

public class SapBOMAsFed {
	@XmlElement(name = "name", namespace = "") 
	 protected String name;
	@XmlElement(name = "sapdescription", namespace = "") 
	 protected String sapdescription;
	@XmlElement(name = "type", namespace = "") 
	 protected String type;
	@XmlElement(name = "specSub", namespace = "") 
	 protected String specSub;
	@XmlElement(name = "sapType", namespace = "") 
	 protected String sapType;
	@XmlElement(name = "subAltGroup", namespace = "") 
	 protected String subAltGroup;
	@XmlElement(name = "bomQuantity", namespace = "") 
	 protected String bomQuantity;
	@XmlElement(name = "uom", namespace = "") 
	 protected String uom;
	@XmlElement(name = "optionalcomponent", namespace = "") 
	 protected String optionalcomponent;
	@XmlElement(name = "transportPart", namespace = "") 
	 protected String transportPart;
	@XmlElement(name = "comments", namespace = "") 
	 protected String comments;
	@XmlElement(name = "authorized", namespace = "") 
	 protected String authorized;
	@XmlElement(name = "authorizedUse", namespace = "") 
	 protected String authorizedUse;
	@XmlElement(name = "authorizedProduce", namespace = "") 
	 protected String authorizedProduce;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSapdescription() {
		return sapdescription;
	}
	public void setSapdescription(String sapdescription) {
		this.sapdescription = sapdescription;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getSpecSub() {
		return specSub;
	}
	public void setSpecSub(String specSub) {
		this.specSub = specSub;
	}
	public String getSapType() {
		return sapType;
	}
	public void setSapType(String sapType) {
		this.sapType = sapType;
	}
	public String getSubAltGroup() {
		return subAltGroup;
	}
	public void setSubAltGroup(String subAltGroup) {
		this.subAltGroup = subAltGroup;
	}
	public String getBomQuantity() {
		return bomQuantity;
	}
	public void setBomQuantity(String bomQuantity) {
		this.bomQuantity = bomQuantity;
	}
	public String getUom() {
		return uom;
	}
	public void setUom(String uom) {
		this.uom = uom;
	}
	public String getOptionalcomponent() {
		return optionalcomponent;
	}
	public void setOptionalcomponent(String optionalcomponent) {
		this.optionalcomponent = optionalcomponent;
	}
	public String getTransportPart() {
		return transportPart;
	}
	public void setTransportPart(String transportPart) {
		this.transportPart = transportPart;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public String getAuthorized() {
		return authorized;
	}
	public void setAuthorized(String authorized) {
		this.authorized = authorized;
	}
	public String getAuthorizedUse() {
		return authorizedUse;
	}
	public void setAuthorizedUse(String authorizedUse) {
		this.authorizedUse = authorizedUse;
	}
	public String getAuthorizedProduce() {
		return authorizedProduce;
	}
	public void setAuthorizedProduce(String authorizedProduce) {
		this.authorizedProduce = authorizedProduce;
	}
	 
	 
	 
}
