//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"name",
		"type",
		"description",
		"state",
		"library",
		"classificationpath",
		"hasClassAccess"

})
public class SecurityClass {
	@XmlElement(name = "Name", namespace = "") 
	 protected String name;
	@XmlElement(name = "Type", namespace = "") 
	 protected String type;
	@XmlElement(name = "Description", namespace = "") 
	 protected String description;
	@XmlElement(name = "State", namespace = "") 
	 protected String state;
	@XmlElement(name = "Library", namespace = "") 
	 protected String library;
	@XmlElement(name = "ClassificationPath", namespace = "") 
	 protected String classificationpath;
	@XmlElement(name = "HasClassAccess", namespace = "") 
	 protected String hasClassAccess;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getLibrary() {
		return library;
	}
	public void setLibrary(String library) {
		this.library = library;
	}
	public String getClassificationpath() {
		return classificationpath;
	}
	public void setClassificationpath(String classificationpath) {
		this.classificationpath = classificationpath;
	}
	public String getHasClassAccess() {
		return hasClassAccess;
	}
	public void setHasClassAccess(String hasClassAccess) {
		this.hasClassAccess = hasClassAccess;
	}
}
