//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"name",
		"revision",
		"title",
		"expirationdate",
		"shelflife",
		"tempreturegroup",
		"humiditygroup",
		"transportfreezeprotection",
		"transportheatprotection",
		"boundrycondition",
		"stabilityreport"

})
public class StabilityResult {
	@XmlElement(name = "ProductPartName", namespace = "") 
	 protected String name;
	@XmlElement(name = "ProductPartRevision", namespace = "") 
	 protected String revision;
	@XmlElement(name = "ProductPartTitle", namespace = "") 
	 protected String title;
	@XmlElement(name = "ProductExpirationDateRequired", namespace = "") 
	 protected String expirationdate;
	@XmlElement(name = "TotalShelfLifeDays", namespace = "") 
	 protected String shelflife;
	@XmlElement(name = "TemperatureGroup", namespace = "") 
	 protected String tempreturegroup;
	@XmlElement(name = "HumidityGroup", namespace = "") 
	 protected String humiditygroup;
	@XmlElement(name = "TransportFreezeProtection", namespace = "") 
	 protected String transportfreezeprotection;
	@XmlElement(name = "TransportHeatProtection", namespace = "") 
	 protected String transportheatprotection;
	@XmlElement(name = "BoundaryConditions", namespace = "") 
	 protected String boundrycondition;
	@XmlElement(name = "StabilityReport", namespace = "") 
	 protected String stabilityreport;
	
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getRevision() {
		return revision;
	}
	public void setRevision(String revision) {
		this.revision = revision;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getExpirationdate() {
		return expirationdate;
	}
	public void setExpirationdate(String expirationdate) {
		this.expirationdate = expirationdate;
	}
	public String getShelflife() {
		return shelflife;
	}
	public void setShelflife(String shelflife) {
		this.shelflife = shelflife;
	}
	public String getTempreturegroup() {
		return tempreturegroup;
	}
	public void setTempreturegroup(String tempreturegroup) {
		this.tempreturegroup = tempreturegroup;
	}
	public String getHumiditygroup() {
		return humiditygroup;
	}
	public void setHumiditygroup(String humiditygroup) {
		this.humiditygroup = humiditygroup;
	}
	public String getTransportfreezeprotection() {
		return transportfreezeprotection;
	}
	public void setTransportfreezeprotection(String transportfreezeprotection) {
		this.transportfreezeprotection = transportfreezeprotection;
	}
	public String getTransportheatprotection() {
		return transportheatprotection;
	}
	public void setTransportheatprotection(String transportheatprotection) {
		this.transportheatprotection = transportheatprotection;
	}
	public String getBoundrycondition() {
		return boundrycondition;
	}
	public void setBoundrycondition(String boundrycondition) {
		this.boundrycondition = boundrycondition;
	}
	public String getStabilityreport() {
		return stabilityreport;
	}
	public void setStabilityreport(String stabilityreport) {
		this.stabilityreport = stabilityreport;
	}
	
	
	
	
	
	
	
	

	
}
