//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//


package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"ufiName",
		"ufiObject"

})
public class UniqueFormulaIdentifier {
	@XmlElement(name = "UFIName", namespace = "") 
	 protected String ufiName;
	@XmlElement(name = "UFIObject", namespace = "") 
	 protected String ufiObject;
	
	public String getUfiName() {
		return ufiName;
	}
	public void setUfiName(String ufiName) {
		this.ufiName = ufiName;
	}
	public String getUfiObject() {
		return ufiObject;
	}
	public void setUfiObject(String ufiObject) {
		this.ufiObject = ufiObject;
	}

	
}
