//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//

package com.pdfview.impl.FPP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"warehousingClassificationData",
"corrosive"

})
@XmlRootElement(name = "WarehouseClassification", namespace = "")
public class WarehouseClassification {
	@XmlElement(name = "WarehousingClassificationData", namespace = "") 
	 protected String warehousingClassificationData;
	@XmlElement(name = "Corrosive", namespace = "") 
	 protected String corrosive;
	public String getWarehousingClassificationData() {
		return warehousingClassificationData;
	}
	public void setWarehousingClassificationData(String warehousingClassificationData) {
		this.warehousingClassificationData = warehousingClassificationData;
	}
	public String getCorrosive() {
		return corrosive;
	}
	public void setCorrosive(String corrosive) {
		this.corrosive = corrosive;
	}
	
}
