//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//

package com.pdfview.impl.APP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"title",
"description",
"type",
"assemblyType",
"originator",
"lastUpdateUser",
"revision",
"originated",
"segment",
"releasePhase",
"owner",
"releaseDate",
"effectivityDate",
"expirationDate",
"previousRevisionObsoleteDate",
"reasonforChange",
"isProductCertificationorLocalStandardsComplianceStatementRequired",
"productDoseperUse",
"productDoseperUseUoM",
"expectedFrequencyofUse",
"expectedFrequencyofUseUoM",
"modeofProductDisposal",
"lifeCycleStatus",
"pDTemplatestopgBrandName",
"productExtraVariant",
"baseUnitOfMeasure",
"onshelfProductDensity",
"densityUOM",
"entryBaseQuantity",
"bomBaseQuantity",
"localDescription",
"otherNames",
"intendedMarketsName",
"replacedByProductID",
"dSMProductSize",
"uniqueFormulaIdentifier",
"comment",
"archiveDate",
"archiveComment",
"role"

})
@XmlRootElement(name = "Attributes", namespace = "")
public class Attributes {

	@XmlElement(name = "Title", namespace = "") 
	 protected String title;
	@XmlElement(name = "Description", namespace = "") 
	 protected String description;
	@XmlElement(name = "Type", namespace = "") 
	 protected String type;
	@XmlElement(name = "AssemblyType", namespace = "") 
	 protected String assemblyType;
	@XmlElement(name = "Originator", namespace = "") 
	 protected String originator;
	@XmlElement(name = "LastUpdateUser", namespace = "") 
	 protected String lastUpdateUser;
	@XmlElement(name = "Revision", namespace = "") 
	 protected String revision;
	@XmlElement(name = "Originated", namespace = "") 
	 protected String originated;
	@XmlElement(name = "Segment", namespace = "") 
	 protected String segment;
	@XmlElement(name = "ReleasePhase", namespace = "") 
	 protected String releasePhase;
	@XmlElement(name = "Owner", namespace = "") 
	 protected String owner;
	@XmlElement(name = "ReleaseDate", namespace = "") 
	 protected String releaseDate;
	@XmlElement(name = "EffectivityDate", namespace = "") 
	 protected String effectivityDate;
	@XmlElement(name = "ExpirationDate", namespace = "") 
	 protected String expirationDate;
	@XmlElement(name = "PreviousRevisionObsoleteDate", namespace = "") 
	 protected String previousRevisionObsoleteDate;
	@XmlElement(name = "ReasonforChange", namespace = "") 
	 protected String reasonforChange;
	@XmlElement(name = "IsProductCertificationorLocalStandardsComplianceStatementRequired", namespace = "") 
	 protected String isProductCertificationorLocalStandardsComplianceStatementRequired;
	@XmlElement(name = "ProductDoseperUse", namespace = "") 
	 protected String productDoseperUse;
	@XmlElement(name = "ProductDoseperUseUoM", namespace = "") 
	 protected String productDoseperUseUoM;
	@XmlElement(name = "ExpectedFrequencyofUse", namespace = "") 
	 protected String expectedFrequencyofUse;
	@XmlElement(name = "ExpectedFrequencyofUseUoM", namespace = "") 
	 protected String expectedFrequencyofUseUoM;
	@XmlElement(name = "ModeofProductDisposal", namespace = "") 
	 protected String modeofProductDisposal;
	@XmlElement(name = "LifeCycleStatus", namespace = "") 
	 protected String lifeCycleStatus;
	@XmlElement(name = "PDTemplatestopgBrandName", namespace = "") 
	 protected String pDTemplatestopgBrandName;
	@XmlElement(name = "ProductExtraVariant", namespace = "") 
	 protected String productExtraVariant;
	@XmlElement(name = "BaseUnitOfMeasure", namespace = "") 
	 protected String baseUnitOfMeasure;
	@XmlElement(name = "OnshelfProductDensity", namespace = "") 
	 protected String onshelfProductDensity;
	@XmlElement(name = "DensityUOM", namespace = "") 
	 protected String densityUOM;
	@XmlElement(name = "EntryBaseQuantity", namespace = "") 
	 protected String entryBaseQuantity;
	@XmlElement(name = "BomBaseQuantity", namespace = "") 
	 protected String bomBaseQuantity;
	@XmlElement(name = "LocalDescription", namespace = "") 
	 protected String localDescription;
	@XmlElement(name = "OtherNames", namespace = "") 
	 protected String otherNames;
	@XmlElement(name = "IntendedMarketsName", namespace = "") 
	 protected String intendedMarketsName;
	@XmlElement(name = "ReplacedByProductID", namespace = "") 
	 protected String replacedByProductID;
	@XmlElement(name = "DSMProductSize", namespace = "") 
	 protected String dSMProductSize;
	@XmlElement(name = "UniqueFormulaIdentifier", namespace = "") 
	 protected String uniqueFormulaIdentifier;
	@XmlElement(name = "Comment", namespace = "") 
	 protected String comment;
	@XmlElement(name = "ArchiveDate", namespace = "") 
	 protected String archiveDate;
	@XmlElement(name = "ArchiveComment", namespace = "") 
	 protected String archiveComment;
	@XmlElement(name = "Role", namespace = "")
	protected String role;
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getAssemblyType() {
		return assemblyType;
	}
	public void setAssemblyType(String assemblyType) {
		this.assemblyType = assemblyType;
	}
	public String getOriginator() {
		return originator;
	}
	public void setOriginator(String originator) {
		this.originator = originator;
	}
	public String getLastUpdateUser() {
		return lastUpdateUser;
	}
	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}
	public String getRevision() {
		return revision;
	}
	public void setRevision(String revision) {
		this.revision = revision;
	}
	public String getOriginated() {
		return originated;
	}
	public void setOriginated(String originated) {
		this.originated = originated;
	}
	public String getSegment() {
		return segment;
	}
	public void setSegment(String segment) {
		this.segment = segment;
	}
	public String getReleasePhase() {
		return releasePhase;
	}
	public void setReleasePhase(String releasePhase) {
		this.releasePhase = releasePhase;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getReleaseDate() {
		return releaseDate;
	}
	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}
	public String getEffectivityDate() {
		return effectivityDate;
	}
	public void setEffectivityDate(String effectivityDate) {
		this.effectivityDate = effectivityDate;
	}
	public String getExpirationDate() {
		return expirationDate;
	}
	public void setExpirationDate(String expirationDate) {
		this.expirationDate = expirationDate;
	}
	public String getPreviousRevisionObsoleteDate() {
		return previousRevisionObsoleteDate;
	}
	public void setPreviousRevisionObsoleteDate(String previousRevisionObsoleteDate) {
		this.previousRevisionObsoleteDate = previousRevisionObsoleteDate;
	}
	public String getReasonforChange() {
		return reasonforChange;
	}
	public void setReasonforChange(String reasonforChange) {
		this.reasonforChange = reasonforChange;
	}
	public String getIsProductCertificationorLocalStandardsComplianceStatementRequired() {
		return isProductCertificationorLocalStandardsComplianceStatementRequired;
	}
	public void setIsProductCertificationorLocalStandardsComplianceStatementRequired(
			String isProductCertificationorLocalStandardsComplianceStatementRequired) {
		this.isProductCertificationorLocalStandardsComplianceStatementRequired = isProductCertificationorLocalStandardsComplianceStatementRequired;
	}
	public String getProductDoseperUse() {
		return productDoseperUse;
	}
	public void setProductDoseperUse(String productDoseperUse) {
		this.productDoseperUse = productDoseperUse;
	}
	public String getProductDoseperUseUoM() {
		return productDoseperUseUoM;
	}
	public void setProductDoseperUseUoM(String productDoseperUseUoM) {
		this.productDoseperUseUoM = productDoseperUseUoM;
	}
	public String getExpectedFrequencyofUse() {
		return expectedFrequencyofUse;
	}
	public void setExpectedFrequencyofUse(String expectedFrequencyofUse) {
		this.expectedFrequencyofUse = expectedFrequencyofUse;
	}
	public String getExpectedFrequencyofUseUoM() {
		return expectedFrequencyofUseUoM;
	}
	public void setExpectedFrequencyofUseUoM(String expectedFrequencyofUseUoM) {
		this.expectedFrequencyofUseUoM = expectedFrequencyofUseUoM;
	}
	public String getModeofProductDisposal() {
		return modeofProductDisposal;
	}
	public void setModeofProductDisposal(String modeofProductDisposal) {
		this.modeofProductDisposal = modeofProductDisposal;
	}
	public String getLifeCycleStatus() {
		return lifeCycleStatus;
	}
	public void setLifeCycleStatus(String lifeCycleStatus) {
		this.lifeCycleStatus = lifeCycleStatus;
	}
	public String getpDTemplatestopgBrandName() {
		return pDTemplatestopgBrandName;
	}
	public void setpDTemplatestopgBrandName(String pDTemplatestopgBrandName) {
		this.pDTemplatestopgBrandName = pDTemplatestopgBrandName;
	}
	public String getProductExtraVariant() {
		return productExtraVariant;
	}
	public void setProductExtraVariant(String productExtraVariant) {
		this.productExtraVariant = productExtraVariant;
	}
	public String getBaseUnitOfMeasure() {
		return baseUnitOfMeasure;
	}
	public void setBaseUnitOfMeasure(String baseUnitOfMeasure) {
		this.baseUnitOfMeasure = baseUnitOfMeasure;
	}
	public String getOnshelfProductDensity() {
		return onshelfProductDensity;
	}
	public void setOnshelfProductDensity(String onshelfProductDensity) {
		this.onshelfProductDensity = onshelfProductDensity;
	}
	public String getDensityUOM() {
		return densityUOM;
	}
	public void setDensityUOM(String densityUOM) {
		this.densityUOM = densityUOM;
	}
	public String getEntryBaseQuantity() {
		return entryBaseQuantity;
	}
	public void setEntryBaseQuantity(String entryBaseQuantity) {
		this.entryBaseQuantity = entryBaseQuantity;
	}
	public String getBomBaseQuantity() {
		return bomBaseQuantity;
	}
	public void setBomBaseQuantity(String bomBaseQuantity) {
		this.bomBaseQuantity = bomBaseQuantity;
	}
	public String getLocalDescription() {
		return localDescription;
	}
	public void setLocalDescription(String localDescription) {
		this.localDescription = localDescription;
	}
	public String getOtherNames() {
		return otherNames;
	}
	public void setOtherNames(String otherNames) {
		this.otherNames = otherNames;
	}
	public String getIntendedMarketsName() {
		return intendedMarketsName;
	}
	public void setIntendedMarketsName(String intendedMarketsName) {
		this.intendedMarketsName = intendedMarketsName;
	}
	public String getReplacedByProductID() {
		return replacedByProductID;
	}
	public void setReplacedByProductID(String replacedByProductID) {
		this.replacedByProductID = replacedByProductID;
	}
	public String getdSMProductSize() {
		return dSMProductSize;
	}
	public void setdSMProductSize(String dSMProductSize) {
		this.dSMProductSize = dSMProductSize;
	}
	public String getUniqueFormulaIdentifier() {
		return uniqueFormulaIdentifier;
	}
	public void setUniqueFormulaIdentifier(String uniqueFormulaIdentifier) {
		this.uniqueFormulaIdentifier = uniqueFormulaIdentifier;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public String getArchiveDate() {
		return archiveDate;
	}
	public void setArchiveDate(String archiveDate) {
		this.archiveDate = archiveDate;
	}
	public String getArchiveComment() {
		return archiveComment;
	}
	public void setArchiveComment(String archiveComment) {
		this.archiveComment = archiveComment;
	}
	public String getRole() {
		return role;
	}
	public void setRole(String role) {
		this.role = role;
	}
	
}
