//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:18 AM EDT 
//

package com.pdfview.impl.APP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"country",
"overallClearance",
"psraApproveStatus",
"productRegClassification",
"clearanceNumber",
"countryProductRegistrationNumber",
"regStatus",
"regExpirDate",
"registrationRenewalLeadTime",
"registrationRenewalStatus",
"plantRestriction",
"packingSite",
"manufacturingSite",
"clearanceComments"

})

public class CountryClearance {
	@XmlElement(name = "Country", namespace = "") 
	 protected String country;
	@XmlElement(name = "OverallClearance", namespace = "") 
	 protected String overallClearance;
	@XmlElement(name = "PSRAApproveStatus", namespace = "") 
	 protected String psraApproveStatus;
	@XmlElement(name = "ProductRegClassification", namespace = "") 
	 protected String productRegClassification;
	@XmlElement(name = "ClearanceNumber", namespace = "") 
	 protected String clearanceNumber;
	@XmlElement(name = "CountryProductRegistrationNumber", namespace = "") 
	 protected String countryProductRegistrationNumber;
	@XmlElement(name = "RegStatus", namespace = "") 
	 protected String regStatus;
	@XmlElement(name = "RegExpirDate", namespace = "") 
	 protected String regExpirDate;
	@XmlElement(name = "RegistrationRenewalLeadTime", namespace = "") 
	 protected String registrationRenewalLeadTime;
	@XmlElement(name = "RegistrationRenewalStatus", namespace = "") 
	 protected String registrationRenewalStatus;
	@XmlElement(name = "PlantRestriction", namespace = "") 
	 protected String plantRestriction;
	@XmlElement(name = "PackingSite", namespace = "") 
	 protected String packingSite;
	@XmlElement(name = "ManufacturingSite", namespace = "") 
	 protected String manufacturingSite;
	@XmlElement(name = "ClearanceComments", namespace = "") 
	 protected String clearanceComments;
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getOverallClearance() {
		return overallClearance;
	}
	public void setOverallClearance(String overallClearance) {
		this.overallClearance = overallClearance;
	}

	public String getPsraApproveStatus() {
		return psraApproveStatus;
	}
	public void setPsraApproveStatus(String psraApproveStatus) {
		this.psraApproveStatus = psraApproveStatus;
	}
	public String getProductRegClassification() {
		return productRegClassification;
	}
	public void setProductRegClassification(String productRegClassification) {
		this.productRegClassification = productRegClassification;
	}
	public String getClearanceNumber() {
		return clearanceNumber;
	}
	public void setClearanceNumber(String clearanceNumber) {
		this.clearanceNumber = clearanceNumber;
	}
	public String getCountryProductRegistrationNumber() {
		return countryProductRegistrationNumber;
	}
	public void setCountryProductRegistrationNumber(String countryProductRegistrationNumber) {
		this.countryProductRegistrationNumber = countryProductRegistrationNumber;
	}
	public String getRegStatus() {
		return regStatus;
	}
	public void setRegStatus(String regStatus) {
		this.regStatus = regStatus;
	}
	public String getRegExpirDate() {
		return regExpirDate;
	}
	public void setRegExpirDate(String regExpirDate) {
		this.regExpirDate = regExpirDate;
	}
	public String getRegistrationRenewalLeadTime() {
		return registrationRenewalLeadTime;
	}
	public void setRegistrationRenewalLeadTime(String registrationRenewalLeadTime) {
		this.registrationRenewalLeadTime = registrationRenewalLeadTime;
	}
	public String getRegistrationRenewalStatus() {
		return registrationRenewalStatus;
	}
	public void setRegistrationRenewalStatus(String registrationRenewalStatus) {
		this.registrationRenewalStatus = registrationRenewalStatus;
	}
	public String getPlantRestriction() {
		return plantRestriction;
	}
	public void setPlantRestriction(String plantRestriction) {
		this.plantRestriction = plantRestriction;
	}
	public String getPackingSite() {
		return packingSite;
	}
	public void setPackingSite(String packingSite) {
		this.packingSite = packingSite;
	}
	public String getManufacturingSite() {
		return manufacturingSite;
	}
	public void setManufacturingSite(String manufacturingSite) {
		this.manufacturingSite = manufacturingSite;
	}
	public String getClearanceComments() {
		return clearanceComments;
	}
	public void setClearanceComments(String clearanceComments) {
		this.clearanceComments = clearanceComments;
	}
	
	
}
