//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//

package com.pdfview.impl.APP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "masterDescription", "masterType", "masterOrginator", "masterRev", "masterOriginated",
		"masterSegment", "masterStage", "masterOwner", "masterEffectiveDate", "masterExpirationDate",
		"masterReleaseDate", "masterPreviousRevDate", "masterManufacturingStatus", "masterReasonForChange",
		"masterLocalDescription", "masterOtherNames", "masterComments", "masterObsoleteDate", "masterObsoleteComment",
		"masterBrand", "masterIsBattery", "masterContainsBattery", "masterBatteryType", "masterStoragelimits",
		"masterBaseUnitOfMeasure", "masterStorageInfo", "masterStorageTemp", "masterShippingInfo",
		"masterShippingHazard", "masterTechnology", "masterDensityUOM", "masterOnShelf", "masterSAPBOMQuantity",
		"masterBaseQuantity", "masterIntendedMarkets", "masterProductExtraVarient", "masterTemplate",
		"masterPartFamily", "masterReportedFunction", "masterClass", "masterSubClass", "masterODH", "masterODL",
		"masterODW", "masterIDW", "masterIDL", "masterIDH", "masterDIMENSIONUOM", "masterPackagingMaterialType",
		"masterPackComponentType", "masterPackagingSize", "masterPackagingSizeUOM", "masterPackagingTechnology",
		"masterLabelingInfo", "masterClassification", "masterPrintingProcess", "masterDecorationDetails","masterTitle","masterName","lastUpdateUsers"

})

@XmlRootElement(name = "MasterAttributes", namespace = "")
public class MasterAttributes {

	@XmlElement(name = "MasterDescription", namespace = "")
	protected String masterDescription;
	@XmlElement(name = "MasterType", namespace = "")
	protected String masterType;
	@XmlElement(name = "MasterOrginator", namespace = "")
	protected String masterOrginator;
	@XmlElement(name = "MasterRev", namespace = "")
	protected String masterRev;
	@XmlElement(name = "MasterOriginated", namespace = "")
	protected String masterOriginated;
	@XmlElement(name = "MasterSegment", namespace = "")
	protected String masterSegment;
	@XmlElement(name = "MasterStage", namespace = "")
	protected String masterStage;
	@XmlElement(name = "MasterOwner", namespace = "")
	protected String masterOwner;
	@XmlElement(name = "MasterEffectiveDate", namespace = "")
	protected String masterEffectiveDate;
	@XmlElement(name = "MasterExpirationDate", namespace = "")
	protected String masterExpirationDate;
	@XmlElement(name = "MasterReleaseDate", namespace = "")
	protected String masterReleaseDate;
	@XmlElement(name = "MasterPreviousRevDate", namespace = "")
	protected String masterPreviousRevDate;
	@XmlElement(name = "MasterManufacturingStatus", namespace = "")
	protected String masterManufacturingStatus;
	@XmlElement(name = "MasterReasonForChange", namespace = "")
	protected String masterReasonForChange;
	@XmlElement(name = "MasterLocalDescription", namespace = "")
	protected String masterLocalDescription;
	@XmlElement(name = "MasterOtherNames", namespace = "")
	protected String masterOtherNames;
	@XmlElement(name = "MasterComments", namespace = "")
	protected String masterComments;
	@XmlElement(name = "MasterObsoleteDate", namespace = "")
	protected String masterObsoleteDate;
	@XmlElement(name = "MasterObsoleteComment", namespace = "")
	protected String masterObsoleteComment;
	@XmlElement(name = "MasterBrand", namespace = "")
	protected String masterBrand;
	@XmlElement(name = "MasterIsBattery", namespace = "")
	protected String masterIsBattery;
	@XmlElement(name = "MasterContainsBattery", namespace = "")
	protected String masterContainsBattery;
	@XmlElement(name = "MasterBatteryType", namespace = "")
	protected String masterBatteryType;
	@XmlElement(name = "MasterStoragelimits", namespace = "")
	protected String masterStoragelimits;
	@XmlElement(name = "MasterBaseUnitOfMeasure", namespace = "")
	protected String masterBaseUnitOfMeasure;
	@XmlElement(name = "MasterStorageInfo", namespace = "")
	protected String masterStorageInfo;
	@XmlElement(name = "MasterStorageTemp", namespace = "")
	protected String masterStorageTemp;
	@XmlElement(name = "MasterShippingInfo", namespace = "")
	protected String masterShippingInfo;
	@XmlElement(name = "MasterShippingHazard", namespace = "")
	protected String masterShippingHazard;
	@XmlElement(name = "MasterTechnology", namespace = "")
	protected String masterTechnology;
	@XmlElement(name = "MasterDensityUOM", namespace = "")
	protected String masterDensityUOM;
	@XmlElement(name = "MasterOnShelf", namespace = "")
	protected String masterOnShelf;
	@XmlElement(name = "MasterSAPBOMQuantity", namespace = "")
	protected String masterSAPBOMQuantity;
	@XmlElement(name = "MasterBaseQuantity", namespace = "")
	protected String masterBaseQuantity;
	@XmlElement(name = "MasterIntendedMarkets", namespace = "")
	protected String masterIntendedMarkets;
	@XmlElement(name = "MasterProductExtraVarient", namespace = "")
	protected String masterProductExtraVarient;
	@XmlElement(name = "MasterTemplate", namespace = "")
	protected String masterTemplate;
	@XmlElement(name = "MasterPartFamily", namespace = "")
	protected String masterPartFamily;
	@XmlElement(name = "MasterReportedFunction", namespace = "")
	protected String masterReportedFunction;
	@XmlElement(name = "MasterClass", namespace = "")
	protected String masterClass;
	@XmlElement(name = "MasterSubClass", namespace = "")
	protected String masterSubClass;
	@XmlElement(name = "MasterODH", namespace = "")
	protected String masterODH;
	@XmlElement(name = "MasterODL", namespace = "")
	protected String masterODL;
	@XmlElement(name = "MasterODW", namespace = "")
	protected String masterODW;
	@XmlElement(name = "MasterIDW", namespace = "")
	protected String masterIDW;
	@XmlElement(name = "MasterIDL", namespace = "")
	protected String masterIDL;
	@XmlElement(name = "MasterIDH", namespace = "")
	protected String masterIDH;
	@XmlElement(name = "MasterDIMENSIONUOM", namespace = "")
	protected String masterDIMENSIONUOM;
	@XmlElement(name = "MasterPackagingMaterialType", namespace = "")
	protected String masterPackagingMaterialType;
	@XmlElement(name = "MasterPackComponentType", namespace = "")
	protected String masterPackComponentType;
	@XmlElement(name = "MasterPackagingSize", namespace = "")
	protected String masterPackagingSize;
	@XmlElement(name = "MasterPackagingSizeUOM", namespace = "")
	protected String masterPackagingSizeUOM;
	@XmlElement(name = "MasterPackagingTechnology", namespace = "")
	protected String masterPackagingTechnology;
	@XmlElement(name = "MasterLabelingInfo", namespace = "")
	protected String masterLabelingInfo;
	@XmlElement(name = "MasterClassification", namespace = "")
	protected String masterClassification;
	@XmlElement(name = "MasterPrintingProcess", namespace = "")
	protected String masterPrintingProcess;
	@XmlElement(name = "MasterDecorationDetails", namespace = "")
	protected String masterDecorationDetails;
	@XmlElement(name = "MasterTitle", namespace = "")
	protected String masterTitle;
	@XmlElement(name = "LastUpdateUsers", namespace = "")
	protected String lastUpdateUsers;
	@XmlElement(name = "MasterName", namespace = "")
	protected String masterName;
	
	public String getMasterDescription() {
		return masterDescription;
	}
	public void setMasterDescription(String masterDescription) {
		this.masterDescription = masterDescription;
	}
	public String getMasterType() {
		return masterType;
	}
	public void setMasterType(String masterType) {
		this.masterType = masterType;
	}
	public String getMasterOrginator() {
		return masterOrginator;
	}
	public void setMasterOrginator(String masterOrginator) {
		this.masterOrginator = masterOrginator;
	}
	public String getMasterRev() {
		return masterRev;
	}
	public void setMasterRev(String masterRev) {
		this.masterRev = masterRev;
	}
	public String getMasterOriginated() {
		return masterOriginated;
	}
	public void setMasterOriginated(String masterOriginated) {
		this.masterOriginated = masterOriginated;
	}
	public String getMasterSegment() {
		return masterSegment;
	}
	public void setMasterSegment(String masterSegment) {
		this.masterSegment = masterSegment;
	}
	public String getMasterStage() {
		return masterStage;
	}
	public void setMasterStage(String masterStage) {
		this.masterStage = masterStage;
	}
	public String getMasterOwner() {
		return masterOwner;
	}
	public void setMasterOwner(String masterOwner) {
		this.masterOwner = masterOwner;
	}
	public String getMasterEffectiveDate() {
		return masterEffectiveDate;
	}
	public void setMasterEffectiveDate(String masterEffectiveDate) {
		this.masterEffectiveDate = masterEffectiveDate;
	}
	public String getMasterExpirationDate() {
		return masterExpirationDate;
	}
	public void setMasterExpirationDate(String masterExpirationDate) {
		this.masterExpirationDate = masterExpirationDate;
	}
	public String getMasterReleaseDate() {
		return masterReleaseDate;
	}
	public void setMasterReleaseDate(String masterReleaseDate) {
		this.masterReleaseDate = masterReleaseDate;
	}
	public String getMasterPreviousRevDate() {
		return masterPreviousRevDate;
	}
	public void setMasterPreviousRevDate(String masterPreviousRevDate) {
		this.masterPreviousRevDate = masterPreviousRevDate;
	}
	public String getMasterManufacturingStatus() {
		return masterManufacturingStatus;
	}
	public void setMasterManufacturingStatus(String masterManufacturingStatus) {
		this.masterManufacturingStatus = masterManufacturingStatus;
	}
	public String getMasterReasonForChange() {
		return masterReasonForChange;
	}
	public void setMasterReasonForChange(String masterReasonForChange) {
		this.masterReasonForChange = masterReasonForChange;
	}
	public String getMasterLocalDescription() {
		return masterLocalDescription;
	}
	public void setMasterLocalDescription(String masterLocalDescription) {
		this.masterLocalDescription = masterLocalDescription;
	}
	public String getMasterOtherNames() {
		return masterOtherNames;
	}
	public void setMasterOtherNames(String masterOtherNames) {
		this.masterOtherNames = masterOtherNames;
	}
	public String getMasterComments() {
		return masterComments;
	}
	public void setMasterComments(String masterComments) {
		this.masterComments = masterComments;
	}
	public String getMasterObsoleteDate() {
		return masterObsoleteDate;
	}
	public void setMasterObsoleteDate(String masterObsoleteDate) {
		this.masterObsoleteDate = masterObsoleteDate;
	}
	public String getMasterObsoleteComment() {
		return masterObsoleteComment;
	}
	public void setMasterObsoleteComment(String masterObsoleteComment) {
		this.masterObsoleteComment = masterObsoleteComment;
	}
	public String getMasterBrand() {
		return masterBrand;
	}
	public void setMasterBrand(String masterBrand) {
		this.masterBrand = masterBrand;
	}
	public String getMasterIsBattery() {
		return masterIsBattery;
	}
	public void setMasterIsBattery(String masterIsBattery) {
		this.masterIsBattery = masterIsBattery;
	}
	public String getMasterContainsBattery() {
		return masterContainsBattery;
	}
	public void setMasterContainsBattery(String masterContainsBattery) {
		this.masterContainsBattery = masterContainsBattery;
	}
	public String getMasterBatteryType() {
		return masterBatteryType;
	}
	public void setMasterBatteryType(String masterBatteryType) {
		this.masterBatteryType = masterBatteryType;
	}
	public String getMasterStoragelimits() {
		return masterStoragelimits;
	}
	public void setMasterStoragelimits(String masterStoragelimits) {
		this.masterStoragelimits = masterStoragelimits;
	}
	public String getMasterBaseUnitOfMeasure() {
		return masterBaseUnitOfMeasure;
	}
	public void setMasterBaseUnitOfMeasure(String masterBaseUnitOfMeasure) {
		this.masterBaseUnitOfMeasure = masterBaseUnitOfMeasure;
	}
	public String getMasterStorageInfo() {
		return masterStorageInfo;
	}
	public void setMasterStorageInfo(String masterStorageInfo) {
		this.masterStorageInfo = masterStorageInfo;
	}
	public String getMasterStorageTemp() {
		return masterStorageTemp;
	}
	public void setMasterStorageTemp(String masterStorageTemp) {
		this.masterStorageTemp = masterStorageTemp;
	}
	public String getMasterShippingInfo() {
		return masterShippingInfo;
	}
	public void setMasterShippingInfo(String masterShippingInfo) {
		this.masterShippingInfo = masterShippingInfo;
	}
	public String getMasterShippingHazard() {
		return masterShippingHazard;
	}
	public void setMasterShippingHazard(String masterShippingHazard) {
		this.masterShippingHazard = masterShippingHazard;
	}
	public String getMasterTechnology() {
		return masterTechnology;
	}
	public void setMasterTechnology(String masterTechnology) {
		this.masterTechnology = masterTechnology;
	}
	public String getMasterDensityUOM() {
		return masterDensityUOM;
	}
	public void setMasterDensityUOM(String masterDensityUOM) {
		this.masterDensityUOM = masterDensityUOM;
	}
	public String getMasterOnShelf() {
		return masterOnShelf;
	}
	public void setMasterOnShelf(String masterOnShelf) {
		this.masterOnShelf = masterOnShelf;
	}
	public String getMasterSAPBOMQuantity() {
		return masterSAPBOMQuantity;
	}
	public void setMasterSAPBOMQuantity(String masterSAPBOMQuantity) {
		this.masterSAPBOMQuantity = masterSAPBOMQuantity;
	}
	public String getMasterBaseQuantity() {
		return masterBaseQuantity;
	}
	public void setMasterBaseQuantity(String masterBaseQuantity) {
		this.masterBaseQuantity = masterBaseQuantity;
	}
	public String getMasterIntendedMarkets() {
		return masterIntendedMarkets;
	}
	public void setMasterIntendedMarkets(String masterIntendedMarkets) {
		this.masterIntendedMarkets = masterIntendedMarkets;
	}
	public String getMasterProductExtraVarient() {
		return masterProductExtraVarient;
	}
	public void setMasterProductExtraVarient(String masterProductExtraVarient) {
		this.masterProductExtraVarient = masterProductExtraVarient;
	}
	public String getMasterTemplate() {
		return masterTemplate;
	}
	public void setMasterTemplate(String masterTemplate) {
		this.masterTemplate = masterTemplate;
	}
	public String getMasterPartFamily() {
		return masterPartFamily;
	}
	public void setMasterPartFamily(String masterPartFamily) {
		this.masterPartFamily = masterPartFamily;
	}
	public String getMasterReportedFunction() {
		return masterReportedFunction;
	}
	public void setMasterReportedFunction(String masterReportedFunction) {
		this.masterReportedFunction = masterReportedFunction;
	}
	public String getMasterClass() {
		return masterClass;
	}
	public void setMasterClass(String masterClass) {
		this.masterClass = masterClass;
	}
	public String getMasterSubClass() {
		return masterSubClass;
	}
	public void setMasterSubClass(String masterSubClass) {
		this.masterSubClass = masterSubClass;
	}
	public String getMasterODH() {
		return masterODH;
	}
	public void setMasterODH(String masterODH) {
		this.masterODH = masterODH;
	}
	public String getMasterODL() {
		return masterODL;
	}
	public void setMasterODL(String masterODL) {
		this.masterODL = masterODL;
	}
	public String getMasterODW() {
		return masterODW;
	}
	public void setMasterODW(String masterODW) {
		this.masterODW = masterODW;
	}
	public String getMasterIDW() {
		return masterIDW;
	}
	public void setMasterIDW(String masterIDW) {
		this.masterIDW = masterIDW;
	}
	public String getMasterIDL() {
		return masterIDL;
	}
	public void setMasterIDL(String masterIDL) {
		this.masterIDL = masterIDL;
	}
	public String getMasterIDH() {
		return masterIDH;
	}
	public void setMasterIDH(String masterIDH) {
		this.masterIDH = masterIDH;
	}
	public String getMasterDIMENSIONUOM() {
		return masterDIMENSIONUOM;
	}
	public void setMasterDIMENSIONUOM(String masterDIMENSIONUOM) {
		this.masterDIMENSIONUOM = masterDIMENSIONUOM;
	}
	public String getMasterPackagingMaterialType() {
		return masterPackagingMaterialType;
	}
	public void setMasterPackagingMaterialType(String masterPackagingMaterialType) {
		this.masterPackagingMaterialType = masterPackagingMaterialType;
	}
	public String getMasterPackComponentType() {
		return masterPackComponentType;
	}
	public void setMasterPackComponentType(String masterPackComponentType) {
		this.masterPackComponentType = masterPackComponentType;
	}
	public String getMasterPackagingSize() {
		return masterPackagingSize;
	}
	public void setMasterPackagingSize(String masterPackagingSize) {
		this.masterPackagingSize = masterPackagingSize;
	}
	public String getMasterPackagingSizeUOM() {
		return masterPackagingSizeUOM;
	}
	public void setMasterPackagingSizeUOM(String masterPackagingSizeUOM) {
		this.masterPackagingSizeUOM = masterPackagingSizeUOM;
	}
	public String getMasterPackagingTechnology() {
		return masterPackagingTechnology;
	}
	public void setMasterPackagingTechnology(String masterPackagingTechnology) {
		this.masterPackagingTechnology = masterPackagingTechnology;
	}
	public String getMasterLabelingInfo() {
		return masterLabelingInfo;
	}
	public void setMasterLabelingInfo(String masterLabelingInfo) {
		this.masterLabelingInfo = masterLabelingInfo;
	}
	public String getMasterClassification() {
		return masterClassification;
	}
	public void setMasterClassification(String masterClassification) {
		this.masterClassification = masterClassification;
	}
	public String getMasterPrintingProcess() {
		return masterPrintingProcess;
	}
	public void setMasterPrintingProcess(String masterPrintingProcess) {
		this.masterPrintingProcess = masterPrintingProcess;
	}
	public String getMasterDecorationDetails() {
		return masterDecorationDetails;
	}
	public void setMasterDecorationDetails(String masterDecorationDetails) {
		this.masterDecorationDetails = masterDecorationDetails;
	}
	public String getMasterTitle() {
		return masterTitle;
	}
	public void setMasterTitle(String masterTitle) {
		this.masterTitle = masterTitle;
	}
	public String getLastUpdateUsers() {
		return lastUpdateUsers;
	}
	public void setLastUpdateUsers(String lastUpdateUsers) {
		this.lastUpdateUsers = lastUpdateUsers;
	}
	public String getMasterName() {
		return masterName;
	}
	public void setMasterName(String masterName) {
		this.masterName = masterName;
	}
	
}
