//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:09 AM EDT 
//

package com.pdfview.impl.APP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"technology",
"productMarketedChildren",
"productRequireChild",
"productExposedToChildren",
"evaporationRate",
"reserveAcidity",
"reserveAlkalinity",
"shippingHazardClassification",
"shippingInformation",
"storageConditions"

})

@XmlRootElement(name = "StorageTransportationData", namespace = "")
public class StorageTransportationData {
	@XmlElement(name = "Technology", namespace = "") 
	 protected String technology;
	@XmlElement(name = "ProductMarketedChildren", namespace = "") 
	 protected String productMarketedChildren;
	@XmlElement(name = "ProductRequireChild", namespace = "") 
	 protected String productRequireChild;
	@XmlElement(name = "ProductExposedToChildren", namespace = "") 
	 protected String productExposedToChildren;
	@XmlElement(name = "EvaporationRate", namespace = "") 
	 protected String evaporationRate;
	@XmlElement(name = "ReserveAcidity", namespace = "") 
	 protected String reserveAcidity;
	@XmlElement(name = "ReserveAlkalinity", namespace = "") 
	 protected String reserveAlkalinity;
	@XmlElement(name = "ShippingHazardClassification", namespace = "") 
	 protected String shippingHazardClassification;
	@XmlElement(name = "ShippingInformation", namespace = "") 
	 protected String shippingInformation;
	@XmlElement(name = "StorageConditions", namespace = "") 
	 protected String storageConditions;
	
	public String getTechnology() {
		return technology;
	}
	public void setTechnology(String technology) {
		this.technology = technology;
	}
	public String getProductMarketedChildren() {
		return productMarketedChildren;
	}
	public void setProductMarketedChildren(String productMarketedChildren) {
		this.productMarketedChildren = productMarketedChildren;
	}
	public String getProductRequireChild() {
		return productRequireChild;
	}
	public void setProductRequireChild(String productRequireChild) {
		this.productRequireChild = productRequireChild;
	}
	public String getProductExposedToChildren() {
		return productExposedToChildren;
	}
	public void setProductExposedToChildren(String productExposedToChildren) {
		this.productExposedToChildren = productExposedToChildren;
	}
	public String getEvaporationRate() {
		return evaporationRate;
	}
	public void setEvaporationRate(String evaporationRate) {
		this.evaporationRate = evaporationRate;
	}
	public String getReserveAcidity() {
		return reserveAcidity;
	}
	public void setReserveAcidity(String reserveAcidity) {
		this.reserveAcidity = reserveAcidity;
	}
	public String getReserveAlkalinity() {
		return reserveAlkalinity;
	}
	public void setReserveAlkalinity(String reserveAlkalinity) {
		this.reserveAlkalinity = reserveAlkalinity;
	}
	public String getShippingHazardClassification() {
		return shippingHazardClassification;
	}
	public void setShippingHazardClassification(String shippingHazardClassification) {
		this.shippingHazardClassification = shippingHazardClassification;
	}
	public String getShippingInformation() {
		return shippingInformation;
	}
	public void setShippingInformation(String shippingInformation) {
		this.shippingInformation = shippingInformation;
	}
	public String getStorageConditions() {
		return storageConditions;
	}
	public void setStorageConditions(String storageConditions) {
		this.storageConditions = storageConditions;
	}
	
	
}
