name: Generate Javadoc

on:
  workflow_dispatch:

jobs:
  generate-javadoc:
    runs-on: actions-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Javadoc
        run: javadoc -d Documentation -sourcepath Java/pgWidgets -subpackages com 

      - name: Push changes
      run: |
        git config user.name "tekale-v"
        git config user.email "81675926+tekale-v@users.noreply.github.com"
        git add .
        git commit -m "Update report [skip ci]"
        git push
