name: Generate Javadoc

on:
  workflow_dispatch:

jobs:
  generate-javadoc:
    runs-on: actions-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Javadoc
        run: javadoc -d Documentation -sourcepath Java/pgWidgets -subpackages com
