name: Generate and Deploy Javadoc

on:
  workflow_dispatch:
    inputs:
      output-directory:
        description: 'Output directory for Javadoc'
        required: true
        default: 'Documentation'
      source-path:
        description: 'Source path for Javadoc'
        required: true
        default: 'Java/pgWidgets'
      class-path:
        description: 'Classpath for Javadoc'
        required: true
        default: 'D:\\eclipse\\lib\\*;D:\\eclipse\\lib\\docs\\java\\*;D:\\eclipse\\lib\\docs\\javacommon\\*;D:\\eclipse\\lib\\docs\\javaserver\\*'

jobs:
  generate-javadoc:
    runs-on: JavaDoc
    
    permissions:
      pages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate Javadoc
        run: |
          mkdir -p ${{ github.event.inputs.output-directory }}
          javadoc -d ${{ github.event.inputs.output-directory }} -sourcepath ${{ github.event.inputs.source-path }} -subpackages com -classpath "${{ github.event.inputs.class-path }}"
          echo "Javadoc generation completed."
        continue-on-error: true

      - name: Verify Javadoc Generation
        run: |
          echo "Listing contents of ${{ github.event.inputs.output-directory }} directory:"
          ls -R ${{ github.event.inputs.output-directory }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.event.inputs.output-directory }}
