name: Generate Javadoc

on:
  workflow_dispatch:

jobs:
  generate-javadoc:
    runs-on: actions-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Generate Javadoc
        run: javadoc -d Documentation -sourcepath Java/pgWidgets -subpackages com
