name: Run script

on:
   workflow_dispatch:
   
jobs:

  Run-Script:

    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: setup node js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
  
    - name: Run Script
      run: 
        cd ./docs/
        node report.js
      
